
########## Sample size vs extrapolation performance ##########

# Load output df
diff.perc.df <- readRDS("/lustre1/g/sbs_bonebrake/Eugene/Tempdata/Trunlevel_REV_perctrun_EMmean.RData")

wdpc <- "C:/Users/Eugene/Desktop/Paper1_Vis" # PC
wdG15 <- "C:/Users/skywa/Desktop/Paper1_Vis" # Laptop
wdHPC <- "/lustre1/g/sbs_bonebrake/Eugene/Tempdata" # HPC
setwd(wdpc)

diff.perc.df <- readRDS("Trunlevel_REV_perctrun_EMmean.RData")
#diff.perc.df <- readRDS(paste0(save.filename,".RData"))

# Load sample size
vtype <- "RAW" # "PC" or "RAW"
if (vtype == "PC") {vspdir <- "biomod424_BASE_PC"} else if (vtype == "RAW") {vspdir <- "biomod424_BASE_REV"}

#sampledf <- read.csv(paste0("/lustre1/g/sbs_bonebrake/Eugene/SDMin/",vspdir,".csv"))
sampledf <- read.csv(paste0(vspdir,".csv"))

diff.perc.df <- merge(diff.perc.df, sampledf[, c("Species", "Samplesize")], by = "Species")

# Calculate Fp
#study_area <- terra::rast(paste0("/lustre1/g/sbs_bonebrake/Eugene/SDMout/results_",filename1,"/",common.list[[1]],
#                                 projection,common.list[[1]],"_ensemble_TSSbin.tif"))[[1]] # Load any ensemble_TSSbin.tif file generated by SDM
#totalcells <- sum(terra::freq(study_area)[,3])
totalcells <- 125339

diff.perc.df$Full.F <- diff.perc.df$Full.F/totalcells*100
diff.perc.df$TrunI.F <- diff.perc.df$TrunI.F/totalcells*100
diff.perc.df$TrunII.F <- diff.perc.df$TrunII.F/totalcells*100
diff.perc.df$TrunIII.F <- diff.perc.df$TrunIII.F/totalcells*100

### Quick stats ###
simp.stats.df <- diff.perc.df[,c("Species", "Samplesize","Full.F","TrunI.F","TrunII.F","TrunIII.F")]

simp.stats.df$Group <- cut(simp.stats.df$Samplesize, 
                           breaks = c(100, 150, 200, 250), 
                           labels = c("n <= 150", "150 < n <= 200", "200 < n <= 250"))

means_by_size <- aggregate(cbind(Full.F, TrunI.F, TrunII.F, TrunIII.F) ~ Group, 
                           data = simp.stats.df, 
                           FUN = mean, 
                           na.rm = TRUE)
means_by_size

medians_by_size <- aggregate(cbind(Full.F, TrunI.F, TrunII.F, TrunIII.F) ~ Group, 
                             data = simp.stats.df, 
                             FUN = median, 
                             na.rm = TRUE)
medians_by_size

### Regression + scatter plot ###
library(ggplot2)
library(tidyr)

# Format data (restrict to 100-250 sample size)
diff.perc.df1 <- subset(diff.perc.df, Samplesize >= 100 & Samplesize <= 250)
plot_data <- diff.perc.df1 %>%
  pivot_longer(cols = c(Full.F, TrunI.F, TrunII.F, TrunIII.F),
               names_to = "Type",
               values_to = "Value")

# ggplot
extrafont::loadfonts(device="win")
extrafont::loadfonts(device="postscript")

ggplot(plot_data, aes(x = Samplesize, y = Value, color = Type)) +
  geom_point(shape = 1) +
  geom_smooth(method = "lm", se = FALSE) + 
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  scale_color_manual(
    values = c("Full.F" = "black",
               "TrunI.F" = "#364B9A",
               "TrunII.F" = "#4A7BB7",
               "TrunIII.F" = "#6EA6CD"),
    labels = c("Full.F" = "No intentional truncation",
               "TrunI.F" = "10% truncation",
               "TrunII.F" = "20% truncation",
               "TrunIII.F" = "30% truncation")) +
  #coord_cartesian(xlim = c(50, 300)) +
  coord_cartesian(xlim = c(100, 250)) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.8, 0.8, 0.5, 0.8, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=17, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=17, family = "Calibri", vjust=5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_text(size=12.5, family = "Calibri"),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.direction = "vertical",
        legend.position = c(0.98, 0.98),
        legend.justification = c("right", "top"),
        legend.text = element_text(size = 14, family = "Calibri"),
        legend.title = element_blank(),
        legend.key.width = unit(1,"cm")) +
  labs(x = "Number of occurrences",
       y = "False prediciton percentage",
       color = "Legend")

ggsave("Scatterplot.png", width = 28, height = 18, units = "cm", dpi = 1000)


ggplot(plot_data, aes(x = Samplesize, y = Value, color = Type)) +
  #geom_point(shape = 1) +
  geom_smooth(method = "lm", se = FALSE) + 
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  scale_color_manual(
    values = c("Full.F" = "black",
               "TrunI.F" = "#364B9A",
               "TrunII.F" = "#4A7BB7",
               "TrunIII.F" = "#6EA6CD"),
    labels = c("Full.F" = "No intentional truncation",
               "TrunI.F" = "10% truncation",
               "TrunII.F" = "20% truncation",
               "TrunIII.F" = "30% truncation")) +
  #coord_cartesian(xlim = c(50, 300)) +
  coord_cartesian(xlim = c(100, 250)) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.8, 0.8, 0.5, 0.8, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=17, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=17, family = "Calibri", vjust=5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_text(size=12.5, family = "Calibri"),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.direction = "vertical",
        legend.position = c(0.98, 0.07),
        legend.justification = c("right", "bottom"),
        legend.text = element_text(size = 14, family = "Calibri"),
        legend.title = element_blank(),
        legend.key.width = unit(1,"cm")) +
  labs(x = "Number of occurrences",
       y = "False prediciton percentage",
       color = "Legend")

ggsave("Lines_only.png", width = 28, height = 18, units = "cm", dpi = 1000)

