extrafont::loadfonts(device="win")
extrafont::loadfonts(device="postscript")
library(ggplot2)
library(ggpubr)
library(dplyr)

wd <- "/lustre1/g/sbs_bonebrake/Eugene/Paper1_Vis"  # HPC
wdpc <- "C:/Users/Eugene/Desktop/Paper1_Vis_VIF5"  # PC
wdG15 <- "C:/Users/skywa/Desktop/Paper1_Vis_VIF5"  # Laptop

setwd(wdpc)

options(scipen = 999)

save.filename.EMca <- "BINMETH_VIF5_TruncS20_EMca"
save.filename.EMmean <- "BINMETH_VIF5_TruncS20_EMmean"

diff.perc.df <- readRDS(paste0(save.filename.EMca,".RData"))


########## Format data for ggplot ##########

# Calculate total raster cells for percentage calculation
#study_area <- terra::rast("proj_TSSNA_Abisara.bifasciata_ensemble_TSSbin.tif")[[1]] # Load any ensemble_TSSbin.tif file generated by SDM
#totalcells <- sum(terra::freq(study_area)[,3])
totalcells <- 125339

# Define the list of items
items <- c("TSS", "ROC", "POD", "POFD")

# Create an empty data frame to store the results
ggplot_columns <- c("Species","setup","FP","FP.siteperc","FP.rangeperc","FN","FN.siteperc","FN.rangeperc","F","F.siteperc","F.rangeperc","SourceFile")
ggplot.df <- data.frame(matrix(nrow = 0, ncol = length(ggplot_columns)))
colnames(ggplot.df) <- ggplot_columns

# Analysis function
Accuracy_Fun <- function(i, diff.perc.df, source_label) { # Pass diff.perc.df and source_label as an argument
  sp.data <- diff.perc.df[i, ]
  species <- sp.data$Species
  
  for (item in items) {
    # Construct the column name prefixes
    prefix <- paste0(item, ".") # Handle "All" case
    
    # Extract data based on the current item
    t.FP <- sp.data[[paste0(prefix, "FP")]]
    t.FP.siteperc <- t.FP/totalcells*100
    t.FP.rangeperc <- sp.data[[paste0(prefix, "FP.perc")]]
    t.FN <- sp.data[[paste0(prefix, "FN")]]
    t.FN.siteperc <- t.FN/totalcells*100
    t.FN.rangeperc <- sp.data[[paste0(prefix, "FN.perc")]]
    t.F <- sp.data[[paste0(prefix, "F")]]
    t.F.siteperc <- t.F/totalcells*100
    t.F.rangeperc <- sp.data[[paste0(prefix, "F.perc")]]
    
    # Create the data list
    item.data <- list(species, item, t.FP, t.FP.siteperc, t.FP.rangeperc, 
                      t.FN, t.FN.siteperc, t.FN.rangeperc, 
                      t.F, t.F.siteperc, t.F.rangeperc, source_label)
    
    # Add the data to the ggplot data frame
    ggplot.df[nrow(ggplot.df) + 1,] <<- item.data
  }
}

# Load and process EMmean file first
diff.perc.df <- readRDS(paste0(save.filename.EMmean,".RData"))
lapply(1:nrow(diff.perc.df), Accuracy_Fun, diff.perc.df = diff.perc.df, source_label = "EMmean") 

# Store the EMmean results and reset tracking container
full.ggplot.df <- ggplot.df
ggplot.df <- data.frame(matrix(nrow = 0, ncol = length(ggplot_columns)))
colnames(ggplot.df) <- ggplot_columns

# Load and process EMca file second
diff.perc.df <- readRDS(paste0(save.filename.EMca,".RData"))
lapply(1:nrow(diff.perc.df), Accuracy_Fun, diff.perc.df = diff.perc.df, source_label = "EMca") 

# Write bar plot DF
columns <- c("Item","Metric","Mean","SD","Median")
barplot.df <- data.frame(matrix(nrow = 0, ncol = length(columns)))
colnames(barplot.df) <- columns
barplot.siteperc.df <- data.frame(matrix(nrow = 0, ncol = length(columns)))
colnames(barplot.siteperc.df) <- columns
barplot.rangeperc.df <- data.frame(matrix(nrow = 0, ncol = length(columns)))
colnames(barplot.rangeperc.df) <- columns

# Consolidated loop processing across sources and item sets
loop_configs <- list(
  list(source = "EMca", suffix = "_EMca", df_source = ggplot.df),
  list(source = "EMmean", suffix = "_EMmean", df_source = full.ggplot.df)
)

for (config in loop_configs) {
  for (item in items) {
    subset_data <- subset(config$df_source, setup == item & SourceFile == config$source)
    item_name   <- paste0(item, config$suffix)
    
    # Calculate statistics and add to barplot data frames
    barplot.df[nrow(barplot.df) + 1,] <- list(item_name, "tFP", mean(subset_data$FP), sd(subset_data$FP), median(subset_data$FP))
    barplot.df[nrow(barplot.df) + 1,] <- list(item_name, "tFN", mean(subset_data$FN), sd(subset_data$FN), median(subset_data$FN))
    barplot.siteperc.df[nrow(barplot.siteperc.df) + 1,] <- list(item_name, "tFP.siteperc", mean(subset_data$FP.siteperc), sd(subset_data$FP.siteperc), median(subset_data$FP.siteperc))
    barplot.siteperc.df[nrow(barplot.siteperc.df) + 1,] <- list(item_name, "tFN.siteperc", mean(subset_data$FN.siteperc), sd(subset_data$FN.siteperc), median(subset_data$FN.siteperc))
    barplot.rangeperc.df[nrow(barplot.rangeperc.df) + 1,] <- list(item_name, "tFP.rangeperc", mean(subset_data$FP.rangeperc), sd(subset_data$FP.rangeperc), median(subset_data$FP.rangeperc))
    barplot.rangeperc.df[nrow(barplot.rangeperc.df) + 1,] <- list(item_name, "tFN.rangeperc", mean(subset_data$FN.rangeperc), sd(subset_data$FN.rangeperc), median(subset_data$FN.rangeperc))
  }
}

barplot.df$Metric <- factor(barplot.df$Metric, levels = c("tFP", "tFN"))
barplot.siteperc.df$Metric <- factor(barplot.siteperc.df$Metric, levels = c("tFP.siteperc", "tFN.siteperc"))
barplot.rangeperc.df$Metric <- factor(barplot.rangeperc.df$Metric, levels = c("tFP.rangeperc", "tFN.rangeperc"))

replacement_vector <- c(
  "TSS_EMca" = "TSS\n(Committee\naveraging)",
  "ROC_EMca" = "ROC\n(Committee\naveraging)",
  "POD_EMca" = "POD\n(Committee\naveraging)",
  "POFD_EMca" = "POFD\n(Committee\naveraging)",
  "TSS_EMmean" = "TSS\n(Mean)",
  "ROC_EMmean" = "ROC\n(Mean)",
  "POD_EMmean" = "POD\n(Mean)",
  "POFD_EMmean" = "POFD\n(Mean)")

barplot.df$Item <- replacement_vector[barplot.df$Item]
barplot.siteperc.df$Item <- replacement_vector[barplot.siteperc.df$Item]
barplot.rangeperc.df$Item <- replacement_vector[barplot.rangeperc.df$Item]

### Active: Median stacked ###
ggplot(data = barplot.siteperc.df) + 
  geom_bar(aes(x = Item, y = Median, fill = Metric),stat = "identity") +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-1.5),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=2),
        axis.text.x   = element_text(size=15, family = "Calibri"),
        axis.text.y   = element_text(size=15, family = "Calibri"),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.spacing = unit(0.5, "cm"),
        legend.text = element_text(size = 15, family = "Calibri"),
        legend.title = element_text(size = 15, family = "Calibri", margin = margin(b=25))) +
  labs(x = "SDM ensemble algorithm", y = "Median false prediction percentage", fill=" ") +
  scale_fill_manual(values=c("#33BBEE","#882255"), 
                    labels=c("False positive      ","False negative      "))

ggsave("BINmeth_bar_median_VIF5.png", width = 25, height = 18.5, units = "cm", dpi = 800)

