extrafont::loadfonts(device="win")
extrafont::loadfonts(device="postscript")
library(ggplot2)
library(ggpubr)

#wd <- "/lustre1/g/sbs_bonebrake/Eugene/Tempdata"  # HPC
wdpc <- "C:/Users/Eugene/Desktop/Paper1_Vis_VIF5"  # PC
wdG15 <- "C:/Users/skywa/Desktop/Paper1_Vis_VIF5"  # Laptop

setwd(wdG15)

options(scipen = 999)

diff.perc.df <- readRDS(paste0("Biophchndvi_EMca_proj_TSSNA_VIF5_SOUTH_trun20.RData"))
#diff.perc.df <- readRDS(paste0("Biophchndvi_EMca_proj_TSSNA_VIF5_NORTH_trun20.RData"))


########## Format data for ggplot ##########

# Calculate total raster cells for percentage calculation
#study_area <- terra::rast("proj_TSSNA_Abisara.bifasciata_ensemble_TSSbin.tif")[[1]] # Load any ensemble_TSSbin.tif file generated by SDM
#totalcells <- sum(terra::freq(study_area)[,3])
totalcells <- 125339

# Create new DF 
columns <- c("Species","setup",
             "t.FP","t.FP.siteperc","t.FP.rangeperc","t.FN","t.FN.siteperc","t.FN.rangeperc","t.F","t.F.siteperc","t.F.rangeperc")
ggplot.df <- data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(ggplot.df) <- columns

# Write new DF
Accuracy_Fun <- function(i) {
  
  sp.data <- diff.perc.df[i,]
  species <- sp.data$Species
  
  ###
  All.setup <- "All"
  All.t.FP <- sp.data$All.t.FP
  All.t.FP.siteperc <- All.t.FP/totalcells*100
  All.t.FP.rangeperc <- sp.data$All.t.FP.perc
  All.t.FN <- sp.data$All.t.FN
  All.t.FN.siteperc <- All.t.FN/totalcells*100
  All.t.FN.rangeperc <- sp.data$All.t.FN.perc
  All.t.F <- sp.data$All.t.F
  All.t.F.siteperc <- All.t.F/totalcells*100
  All.t.F.rangeperc <- sp.data$All.t.F.perc
  
  All.data <- list(species,All.setup,All.t.FP,All.t.FP.siteperc,All.t.FP.rangeperc,
                   All.t.FN,All.t.FN.siteperc,All.t.FN.rangeperc,All.t.F,All.t.F.siteperc,All.t.F.rangeperc)
  
  ggplot.df[nrow(ggplot.df)+1,] <<- All.data
  
  ###
  BIO.setup <- "BIO"
  BIO.t.FP <- sp.data$BIO.t.FP
  BIO.t.FP.siteperc <- BIO.t.FP/totalcells*100
  BIO.t.FP.rangeperc <- sp.data$BIO.t.FP.perc
  BIO.t.FN <- sp.data$BIO.t.FN
  BIO.t.FN.siteperc <- BIO.t.FN/totalcells*100
  BIO.t.FN.rangeperc <- sp.data$BIO.t.FN.perc
  BIO.t.F <- sp.data$BIO.t.F
  BIO.t.F.siteperc <- BIO.t.F/totalcells*100
  BIO.t.F.rangeperc <- sp.data$BIO.t.F.perc
  
  BIO.data <- list(species,BIO.setup,BIO.t.FP,BIO.t.FP.siteperc,BIO.t.FP.rangeperc,
                   BIO.t.FN,BIO.t.FN.siteperc,BIO.t.FN.rangeperc,BIO.t.F,BIO.t.F.siteperc,BIO.t.F.rangeperc)
  
  ggplot.df[nrow(ggplot.df)+1,] <<- BIO.data
  
  ###
  NOI.setup <- "NOISE"
  NOI.t.FP <- sp.data$NOI.t.FP
  NOI.t.FP.siteperc <- NOI.t.FP/totalcells*100
  NOI.t.FP.rangeperc <- sp.data$NOI.t.FP.perc
  NOI.t.FN <- sp.data$NOI.t.FN
  NOI.t.FN.siteperc <- NOI.t.FN/totalcells*100
  NOI.t.FN.rangeperc <- sp.data$NOI.t.FN.perc
  NOI.t.F <- sp.data$NOI.t.F
  NOI.t.F.siteperc <- NOI.t.F/totalcells*100
  NOI.t.F.rangeperc <- sp.data$NOI.t.F.perc
  
  NOI.data <- list(species,NOI.setup,NOI.t.FP,NOI.t.FP.siteperc,NOI.t.FP.rangeperc,
                   NOI.t.FN,NOI.t.FN.siteperc,NOI.t.FN.rangeperc,NOI.t.F,NOI.t.F.siteperc,NOI.t.F.rangeperc)
  
  ggplot.df[nrow(ggplot.df)+1,] <<- NOI.data
  
}

i=1:nrow(diff.perc.df)

lapply(i,Accuracy_Fun)


###### Plot ######

### False siteperc

Fplot <- ggplot(ggplot.df) + 
  stat_density(aes(x=t.F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  #stat_density(aes(x=t.F, colour=setup), geom="line", linetype=5, position="identity", size=0.55) +
  #stat_density(aes(x=f.F, colour=setup), geom="line", position="identity", size=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false predictions (%)", y = "Density", fill="xyz") +
  scale_color_manual(values=c("#000000","#0077BB","#AA4499")) +
  scale_x_continuous(limits = c(-1.5,17),expand=c(0,0), breaks = seq(0,17,5)) #+
  #scale_y_continuous(expand=c(0.025,0)) # c(a,b): a=relative expansion(%) b=absolute expansion


### False positive siteperc

FPplot <- ggplot(ggplot.df) + 
  stat_density(aes(x=t.FP.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  #stat_density(aes(x=t.F, colour=setup), geom="line", linetype=5, position="identity", size=0.55) +
  #stat_density(aes(x=f.F, colour=setup), geom="line", position="identity", size=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "False positive predictions (%)", y = "Density", fill="xyz") +
  scale_color_manual(values=c("#000000","#0077BB","#AA4499")) +
  scale_x_continuous(limits = c(-0.8,7),expand=c(0,0), breaks = seq(0,7,2)) #+
#scale_y_continuous(expand=c(0.025,0)) # c(a,b): a=relative expansion(%) b=absolute expansion


### False negative siteperc

FNplot <- ggplot(ggplot.df) + 
  stat_density(aes(x=t.FN.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  #stat_density(aes(x=t.F, colour=setup), geom="line", linetype=5, position="identity", size=0.55) +
  #stat_density(aes(x=f.F, colour=setup), geom="line", position="identity", size=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "False negative predictions (%)", y = "Density", fill="xyz") +
  scale_color_manual(values=c("#000000","#0077BB","#AA4499")) +
  scale_x_continuous(limits = c(-1.8,10.5),expand=c(0,0), breaks = seq(0,9,3)) #+
  #scale_y_continuous(expand=c(0.025,0)) # c(a,b): a=relative expansion(%) b=absolute expansion


ggarrange(Fplot, FPplot, FNplot,
          nrow = 3, ncol = 1, align = "v")

ggsave("Bio_VIF5.png", width = 24.5, height = 35, units = "cm", dpi = 1000)




###### Legend ######
ggplot(ggplot.df) + 
  stat_density(aes(x=t.FN, colour=setup), geom="line", position="identity", size=6) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
        axis.title.y  = element_blank(),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        legend.key = element_blank(),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.text = element_text(size = 14, family = "Calibri"),
        legend.title = element_text(size = 14, family = "Calibri"
                                    # , margin = margin(b=20)
        ),
        legend.key.width = unit(1,"cm"),
        legend.key.spacing.x = unit(0.5,'cm')) +
  labs(y = "Density", x = "False predictions", fill="xyz") +
  guides(color = guide_legend(title = "Variables used      ", nrow = 2)) +
  scale_color_manual(values=c("#000000","#0077BB","#AA4499"), 
                     labels=c("All relevant variables","Selected relevant variables only",
                              "Relevant and irrelevant variables"))

ggsave("Bio_legend.png", width = 26, height = 12, units = "cm", dpi = 1200)












###### Bar plot ######

#Fthresh <- 5
#FPthresh <- 1.5
#FNthresh <- 2.5

##OR##

Fpercthresh <- 5
FPpercthresh <- 1.5
FNpercthresh <- 5

Fthresh <- totalcells*Fpercthresh/100
FPthresh <- totalcells*FPpercthresh/100
FNthresh <- totalcells*FNpercthresh/100

### Specify names
setup1 <- "All.t"
name1 <- "All"
setup2 <- "BIO.t"
name2 <- "BIO"
setup3 <- "NOI.t"
name3 <- "NOI"

### Create new DF 
columns <- c("setup","compare","t.F.sp","t.F.sp.perc","t.FP.sp","t.FP.sp.perc","t.FN.sp","t.FN.sp.perc")
ggbar.df <- data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(ggbar.df) <- columns

### Get data
if(!is.na(setup1)) {
  setup1.F.more <- length(diff.perc.df[[paste0(setup1, ".F")]][diff.perc.df[[paste0(setup1, ".F")]] >= Fthresh])
  setup1.F.more.perc <- setup1.F.more / length(diff.perc.df[[paste0(setup1, ".F")]])*100
  setup1.F.less <- length(diff.perc.df[[paste0(setup1, ".F")]][diff.perc.df[[paste0(setup1, ".F")]] < Fthresh])
  setup1.F.less.perc <- setup1.F.less / length(diff.perc.df[[paste0(setup1, ".F")]])*100
  
  setup1.FP.more <- length(diff.perc.df[[paste0(setup1, ".FP")]][diff.perc.df[[paste0(setup1, ".FP")]] >= FPthresh])
  setup1.FP.more.perc <- setup1.FP.more / length(diff.perc.df[[paste0(setup1, ".FP")]])*100
  setup1.FP.less <- length(diff.perc.df[[paste0(setup1, ".FP")]][diff.perc.df[[paste0(setup1, ".FP")]] < FPthresh])
  setup1.FP.less.perc <- setup1.FP.less / length(diff.perc.df[[paste0(setup1, ".FP")]])*100
  
  setup1.FN.more <- length(diff.perc.df[[paste0(setup1, ".FN")]][diff.perc.df[[paste0(setup1, ".FN")]] >= FNthresh])
  setup1.FN.more.perc <- setup1.FN.more / length(diff.perc.df[[paste0(setup1, ".FN")]])*100
  setup1.FN.less <- length(diff.perc.df[[paste0(setup1, ".FN")]][diff.perc.df[[paste0(setup1, ".FN")]] < FNthresh])
  setup1.FN.less.perc <- setup1.FN.less / length(diff.perc.df[[paste0(setup1, ".FN")]])*100
} 

if(!is.na(setup2)) {
  setup2.F.more <- length(diff.perc.df[[paste0(setup2, ".F")]][diff.perc.df[[paste0(setup2, ".F")]] >= Fthresh])
  setup2.F.more.perc <- setup2.F.more / length(diff.perc.df[[paste0(setup2, ".F")]])*100
  setup2.F.less <- length(diff.perc.df[[paste0(setup2, ".F")]][diff.perc.df[[paste0(setup2, ".F")]] < Fthresh])
  setup2.F.less.perc <- setup2.F.less / length(diff.perc.df[[paste0(setup2, ".F")]])*100
  
  setup2.FP.more <- length(diff.perc.df[[paste0(setup2, ".FP")]][diff.perc.df[[paste0(setup2, ".FP")]] >= FPthresh])
  setup2.FP.more.perc <- setup2.FP.more / length(diff.perc.df[[paste0(setup2, ".FP")]])*100
  setup2.FP.less <- length(diff.perc.df[[paste0(setup2, ".FP")]][diff.perc.df[[paste0(setup2, ".FP")]] < FPthresh])
  setup2.FP.less.perc <- setup2.FP.less / length(diff.perc.df[[paste0(setup2, ".FP")]])*100
  
  setup2.FN.more <- length(diff.perc.df[[paste0(setup2, ".FN")]][diff.perc.df[[paste0(setup2, ".FN")]] >= FNthresh])
  setup2.FN.more.perc <- setup2.FN.more / length(diff.perc.df[[paste0(setup2, ".FN")]])*100
  setup2.FN.less <- length(diff.perc.df[[paste0(setup2, ".FN")]][diff.perc.df[[paste0(setup2, ".FN")]] < FNthresh])
  setup2.FN.less.perc <- setup2.FN.less / length(diff.perc.df[[paste0(setup2, ".FN")]])*100
}

if(!is.na(setup3)) {
  setup3.F.more <- length(diff.perc.df[[paste0(setup3, ".F")]][diff.perc.df[[paste0(setup3, ".F")]] >= Fthresh])
  setup3.F.more.perc <- setup3.F.more / length(diff.perc.df[[paste0(setup3, ".F")]])*100
  setup3.F.less <- length(diff.perc.df[[paste0(setup3, ".F")]][diff.perc.df[[paste0(setup3, ".F")]] < Fthresh])
  setup3.F.less.perc <- setup3.F.less / length(diff.perc.df[[paste0(setup3, ".F")]])*100
  
  setup3.FP.more <- length(diff.perc.df[[paste0(setup3, ".FP")]][diff.perc.df[[paste0(setup3, ".FP")]] >= FPthresh])
  setup3.FP.more.perc <- setup3.FP.more / length(diff.perc.df[[paste0(setup3, ".FP")]])*100
  setup3.FP.less <- length(diff.perc.df[[paste0(setup3, ".FP")]][diff.perc.df[[paste0(setup3, ".FP")]] < FPthresh])
  setup3.FP.less.perc <- setup3.FP.less / length(diff.perc.df[[paste0(setup3, ".FP")]])*100
  
  setup3.FN.more <- length(diff.perc.df[[paste0(setup3, ".FN")]][diff.perc.df[[paste0(setup3, ".FN")]] >= FNthresh])
  setup3.FN.more.perc <- setup3.FN.more / length(diff.perc.df[[paste0(setup3, ".FN")]])*100
  setup3.FN.less <- length(diff.perc.df[[paste0(setup3, ".FN")]][diff.perc.df[[paste0(setup3, ".FN")]] < FNthresh])
  setup3.FN.less.perc <- setup3.FN.less / length(diff.perc.df[[paste0(setup3, ".FN")]])*100
}


### Write data
if(!is.na(setup1)) {
  setup1.more.data <- list(name1,"more",setup1.F.more,setup1.F.more.perc,setup1.FP.more,setup1.FP.more.perc,setup1.FN.more,setup1.FN.more.perc)
  setup1.less.data <- list(name1,"less",setup1.F.less,setup1.F.less.perc,setup1.FP.less,setup1.FP.less.perc,setup1.FN.less,setup1.FN.less.perc)
  ggbar.df[1,] <- setup1.more.data
  ggbar.df[2,] <- setup1.less.data
}

if(!is.na(setup2)) {
  setup2.more.data <- list(name2,"more",setup2.F.more,setup2.F.more.perc,setup2.FP.more,setup2.FP.more.perc,setup2.FN.more,setup2.FN.more.perc)
  setup2.less.data <- list(name2,"less",setup2.F.less,setup2.F.less.perc,setup2.FP.less,setup2.FP.less.perc,setup2.FN.less,setup2.FN.less.perc)
  ggbar.df[3,] <- setup2.more.data
  ggbar.df[4,] <- setup2.less.data
}

if(!is.na(setup3)) {
  setup3.more.data <- list(name3,"more",setup3.F.more,setup3.F.more.perc,setup3.FP.more,setup3.FP.more.perc,setup3.FN.more,setup3.FN.more.perc)
  setup3.less.data <- list(name3,"less",setup3.F.less,setup3.F.less.perc,setup3.FP.less,setup3.FP.less.perc,setup3.FN.less,setup3.FN.less.perc)
  ggbar.df[5,] <- setup3.more.data
  ggbar.df[6,] <- setup3.less.data
}


ggbar.df[,4] <- round(ggbar.df[,4], digits = 0)
ggbar.df[,6] <- round(ggbar.df[,6], digits = 0)
ggbar.df[,8] <- round(ggbar.df[,8], digits = 0)

if(ncol(ggbar.df)>=10) {
  ggbar.df[,10] <- round(ggbar.df[,10], digits = 0)}

#outline <- rep(100, times=nrow(ggbar.df))
ggbar.df$outline <- rep(100, times=nrow(ggbar.df))

# Get Y-coordinate of percentage text in bar
library(plyr)
ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.t.F.sp.perc = 100 - (cumsum(t.F.sp.perc) - (0.5 * t.F.sp.perc)))
ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.t.FP.sp.perc = 100 - (cumsum(t.FP.sp.perc) - (0.5 * t.FP.sp.perc)))
ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.t.FN.sp.perc = 100 - (cumsum(t.FN.sp.perc) - (0.5 * t.FN.sp.perc)))


### F
ggplot(ggbar.df, aes(x=setup, y=t.F.sp.perc)) +
  geom_bar(data = subset(ggbar.df, compare == "less"), aes(fill = setup), 
           stat = "identity", position = "stack", width = 0.75) +
  #geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
  #         stat = "identity", fill = NA, size = 0.3, color = "black", width = 0.75) +
  geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
           stat = "identity", fill = NA, size = 0.3, color = c("#000000","#0077BB","#AA4499"), width = 0.75) + # Coloured version
  geom_text(data = subset(ggbar.df, compare == "less"), aes(x = setup, y = pos.t.F.sp.perc, label = paste0(t.F.sp.perc,"%")),
            colour="white", family="Calibri", size=4.5, angle = 270) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=2.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        ###
        axis.ticks = element_blank(), 
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(y=paste0("Percentage of species with less 
than ",Fpercthresh,"% total false prediction"), fill="xyz") +
  scale_fill_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_color_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_y_continuous(position = "right", expand=c(0.005,0))

ggsave("BIObar_F_VIF5.png", width = 4.9, height = 11.7, units = "cm", dpi = 800)


### FP
ggplot(ggbar.df, aes(x=setup, y=t.FP.sp.perc)) +
  geom_bar(data = subset(ggbar.df, compare == "less"), aes(fill = setup), 
           stat = "identity", position = "stack", width = 0.75) +
  #geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
  #         stat = "identity", fill = NA, size = 0.3, color = "black", width = 0.75) +
  geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
           stat = "identity", fill = NA, size = 0.3, color = c("#000000","#0077BB","#AA4499"), width = 0.75) + # Coloured version
  geom_text(data = subset(ggbar.df, compare == "less"), aes(x = setup, y = pos.t.FP.sp.perc, label = paste0(t.FP.sp.perc,"%")),
            colour="white", family="Calibri", size=4.5, angle = 270) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=2.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        ###
        axis.ticks = element_blank(), 
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(y=paste0("Percentage of species with less
than ",FPpercthresh,"% false positive prediction"), fill="xyz") +
  scale_fill_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_color_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_y_continuous(position = "right", expand=c(0.005,0))

ggsave("BIObar_FP_VIF5.png", width = 4.9, height = 11.7, units = "cm", dpi = 800)


### FN
ggplot(ggbar.df, aes(x=setup, y=t.FN.sp.perc)) +
  geom_bar(data = subset(ggbar.df, compare == "less"), aes(fill = setup), 
           stat = "identity", position = "stack", width = 0.75) +
  #geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
  #         stat = "identity", fill = NA, size = 0.3, color = "black", width = 0.75) +
  geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
           stat = "identity", fill = NA, size = 0.3, color = c("#000000","#0077BB","#AA4499"), width = 0.75) + # Coloured version
  geom_text(data = subset(ggbar.df, compare == "less"), aes(x = setup, y = pos.t.FN.sp.perc, label = paste0(t.FN.sp.perc,"%")),
            colour="white", family="Calibri", size=4.5, angle = 270) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=2.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        ###
        axis.ticks = element_blank(), 
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(y=paste0("Percentage of species with less
than ",FNpercthresh,"% false negative prediction"), fill="xyz") +
  scale_fill_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_color_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_y_continuous(position = "right", expand=c(0.005,0))

ggsave("BIObar_FN_VIF5.png", width = 4.9, height = 11.7, units = "cm", dpi = 800)





































###### Percentage plot ######

### False percentage

Fplot <- ggplot(ggplot.df) + 
  stat_density(aes(x=t.F.perc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  #stat_density(aes(x=t.F, colour=setup), geom="line", linetype=5, position="identity", size=0.55) +
  #stat_density(aes(x=f.F, colour=setup), geom="line", position="identity", size=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=17, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=17, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false prediction percentage (%)", y = "Density", fill="xyz") +
  scale_color_manual(values=c("#000000","#0077BB","#AA4499")) +
  scale_x_continuous(limits = c(0,100),expand=c(0,0), breaks = seq(0,100,25)) +
  scale_y_continuous(expand=c(0.025,0)) # c(a,b): a=relative expansion(%) b=absolute expansion


### False positive percentage

FPplot <- ggplot(ggplot.df) + 
  stat_density(aes(x=t.FP.perc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  #stat_density(aes(x=t.F, colour=setup), geom="line", linetype=5, position="identity", size=0.55) +
  #stat_density(aes(x=f.F, colour=setup), geom="line", position="identity", size=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=17, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=17, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "False positive prediction percentage (%)", y = "Density", fill="xyz") +
  scale_color_manual(values=c("#000000","#0077BB","#AA4499")) +
  scale_x_continuous(limits = c(-20,100),expand=c(0,0), breaks = seq(0,100,25)) +
  scale_y_continuous(expand=c(0.025,0)) # c(a,b): a=relative expansion(%) b=absolute expansion


### False negative percentage

FNplot <- ggplot(ggplot.df) + 
  stat_density(aes(x=t.FN.perc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  #stat_density(aes(x=t.F, colour=setup), geom="line", linetype=5, position="identity", size=0.55) +
  #stat_density(aes(x=f.F, colour=setup), geom="line", position="identity", size=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=17, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=17, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "False negative prediction percentage (%)", y = "Density", fill="xyz") +
  scale_color_manual(values=c("#000000","#0077BB","#AA4499")) +
  scale_x_continuous(limits = c(-10,70),expand=c(0,0), breaks = seq(0,60,20)) +
  scale_y_continuous(expand=c(0.025,0)) # c(a,b): a=relative expansion(%) b=absolute expansion


ggarrange(Fplot, FPplot, FNplot,
          nrow = 3, ncol = 1, align = "v")

ggsave("Bio.png", width = 24.5, height = 35, units = "cm", dpi = 1000)


###### Legend ######
ggplot(ggplot.df) + 
  stat_density(aes(x=t.FN.perc, colour=setup), geom="line", position="identity", size=6) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
        axis.title.y  = element_blank(),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        legend.key = element_blank(),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.text = element_text(size = 14, family = "Calibri"),
        legend.title = element_text(size = 14, family = "Calibri"
                                    # , margin = margin(b=20)
        ),
        legend.key.width = unit(1,"cm"),
        legend.key.spacing.x = unit(0.5,'cm')) +
  labs(y = "Density", x = "False predictions", fill="xyz") +
  guides(color = guide_legend(title = "Variables used      ", nrow = 2)) +
  scale_color_manual(values=c("#000000","#0077BB","#AA4499"), 
                     labels=c("Relevant variables only","Selected relevant variables only",
                              "Relevant and irrelevant variables"))

ggsave("Bio_legend.png", width = 26, height = 12, units = "cm", dpi = 1200)


###### Bar plot ######

Fthresh <- 60
FPthresh <- 35
FNthresh <- 20


### Specify names
setup1 <- "All.t"
name1 <- "All"
setup2 <- "BIO.t"
name2 <- "BIO"
setup3 <- "NOI.t"
name3 <- "NOI"
setup4 <- NA
name4 <- NA
setup5 <- NA
name5 <- NA
setup6 <- NA
name6 <- NA
setup7 <- NA
name7 <- NA
setup8 <- NA
name8 <- NA

### Create new DF 
columns <- c("setup","compare","t.F.sp","t.F.sp.perc","t.FP.sp","t.FP.sp.perc","t.FN.sp","t.FN.sp.perc")
ggbar.df <- data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(ggbar.df) <- columns

### Get data
if(!is.na(setup1)) {
  setup1.F.more <- length(diff.perc.df[[paste0(setup1, ".F.perc")]][diff.perc.df[[paste0(setup1, ".F.perc")]] >= Fthresh])
  setup1.F.more.perc <- setup1.F.more / length(diff.perc.df[[paste0(setup1, ".F.perc")]])*100
  setup1.F.less <- length(diff.perc.df[[paste0(setup1, ".F.perc")]][diff.perc.df[[paste0(setup1, ".F.perc")]] < Fthresh])
  setup1.F.less.perc <- setup1.F.less / length(diff.perc.df[[paste0(setup1, ".F.perc")]])*100
  
  setup1.FP.more <- length(diff.perc.df[[paste0(setup1, ".FP.perc")]][diff.perc.df[[paste0(setup1, ".FP.perc")]] >= FPthresh])
  setup1.FP.more.perc <- setup1.FP.more / length(diff.perc.df[[paste0(setup1, ".FP.perc")]])*100
  setup1.FP.less <- length(diff.perc.df[[paste0(setup1, ".FP.perc")]][diff.perc.df[[paste0(setup1, ".FP.perc")]] < FPthresh])
  setup1.FP.less.perc <- setup1.FP.less / length(diff.perc.df[[paste0(setup1, ".FP.perc")]])*100
  
  setup1.FN.more <- length(diff.perc.df[[paste0(setup1, ".FN.perc")]][diff.perc.df[[paste0(setup1, ".FN.perc")]] >= FNthresh])
  setup1.FN.more.perc <- setup1.FN.more / length(diff.perc.df[[paste0(setup1, ".FN.perc")]])*100
  setup1.FN.less <- length(diff.perc.df[[paste0(setup1, ".FN.perc")]][diff.perc.df[[paste0(setup1, ".FN.perc")]] < FNthresh])
  setup1.FN.less.perc <- setup1.FN.less / length(diff.perc.df[[paste0(setup1, ".FN.perc")]])*100
} 

if(!is.na(setup2)) {
  setup2.F.more <- length(diff.perc.df[[paste0(setup2, ".F.perc")]][diff.perc.df[[paste0(setup2, ".F.perc")]] >= Fthresh])
  setup2.F.more.perc <- setup2.F.more / length(diff.perc.df[[paste0(setup2, ".F.perc")]])*100
  setup2.F.less <- length(diff.perc.df[[paste0(setup2, ".F.perc")]][diff.perc.df[[paste0(setup2, ".F.perc")]] < Fthresh])
  setup2.F.less.perc <- setup2.F.less / length(diff.perc.df[[paste0(setup2, ".F.perc")]])*100
  
  setup2.FP.more <- length(diff.perc.df[[paste0(setup2, ".FP.perc")]][diff.perc.df[[paste0(setup2, ".FP.perc")]] >= FPthresh])
  setup2.FP.more.perc <- setup2.FP.more / length(diff.perc.df[[paste0(setup2, ".FP.perc")]])*100
  setup2.FP.less <- length(diff.perc.df[[paste0(setup2, ".FP.perc")]][diff.perc.df[[paste0(setup2, ".FP.perc")]] < FPthresh])
  setup2.FP.less.perc <- setup2.FP.less / length(diff.perc.df[[paste0(setup2, ".FP.perc")]])*100
  
  setup2.FN.more <- length(diff.perc.df[[paste0(setup2, ".FN.perc")]][diff.perc.df[[paste0(setup2, ".FN.perc")]] >= FNthresh])
  setup2.FN.more.perc <- setup2.FN.more / length(diff.perc.df[[paste0(setup2, ".FN.perc")]])*100
  setup2.FN.less <- length(diff.perc.df[[paste0(setup2, ".FN.perc")]][diff.perc.df[[paste0(setup2, ".FN.perc")]] < FNthresh])
  setup2.FN.less.perc <- setup2.FN.less / length(diff.perc.df[[paste0(setup2, ".FN.perc")]])*100
}

if(!is.na(setup3)) {
  setup3.F.more <- length(diff.perc.df[[paste0(setup3, ".F.perc")]][diff.perc.df[[paste0(setup3, ".F.perc")]] >= Fthresh])
  setup3.F.more.perc <- setup3.F.more / length(diff.perc.df[[paste0(setup3, ".F.perc")]])*100
  setup3.F.less <- length(diff.perc.df[[paste0(setup3, ".F.perc")]][diff.perc.df[[paste0(setup3, ".F.perc")]] < Fthresh])
  setup3.F.less.perc <- setup3.F.less / length(diff.perc.df[[paste0(setup3, ".F.perc")]])*100
  
  setup3.FP.more <- length(diff.perc.df[[paste0(setup3, ".FP.perc")]][diff.perc.df[[paste0(setup3, ".FP.perc")]] >= FPthresh])
  setup3.FP.more.perc <- setup3.FP.more / length(diff.perc.df[[paste0(setup3, ".FP.perc")]])*100
  setup3.FP.less <- length(diff.perc.df[[paste0(setup3, ".FP.perc")]][diff.perc.df[[paste0(setup3, ".FP.perc")]] < FPthresh])
  setup3.FP.less.perc <- setup3.FP.less / length(diff.perc.df[[paste0(setup3, ".FP.perc")]])*100
  
  setup3.FN.more <- length(diff.perc.df[[paste0(setup3, ".FN.perc")]][diff.perc.df[[paste0(setup3, ".FN.perc")]] >= FNthresh])
  setup3.FN.more.perc <- setup3.FN.more / length(diff.perc.df[[paste0(setup3, ".FN.perc")]])*100
  setup3.FN.less <- length(diff.perc.df[[paste0(setup3, ".FN.perc")]][diff.perc.df[[paste0(setup3, ".FN.perc")]] < FNthresh])
  setup3.FN.less.perc <- setup3.FN.less / length(diff.perc.df[[paste0(setup3, ".FN.perc")]])*100
}


### Write data
if(!is.na(setup1)) {
  setup1.more.data <- list(name1,"more",setup1.F.more,setup1.F.more.perc,setup1.FP.more,setup1.FP.more.perc,setup1.FN.more,setup1.FN.more.perc)
  setup1.less.data <- list(name1,"less",setup1.F.less,setup1.F.less.perc,setup1.FP.less,setup1.FP.less.perc,setup1.FN.less,setup1.FN.less.perc)
  ggbar.df[1,] <- setup1.more.data
  ggbar.df[2,] <- setup1.less.data
}

if(!is.na(setup2)) {
  setup2.more.data <- list(name2,"more",setup2.F.more,setup2.F.more.perc,setup2.FP.more,setup2.FP.more.perc,setup2.FN.more,setup2.FN.more.perc)
  setup2.less.data <- list(name2,"less",setup2.F.less,setup2.F.less.perc,setup2.FP.less,setup2.FP.less.perc,setup2.FN.less,setup2.FN.less.perc)
  ggbar.df[3,] <- setup2.more.data
  ggbar.df[4,] <- setup2.less.data
}

if(!is.na(setup3)) {
  setup3.more.data <- list(name3,"more",setup3.F.more,setup3.F.more.perc,setup3.FP.more,setup3.FP.more.perc,setup3.FN.more,setup3.FN.more.perc)
  setup3.less.data <- list(name3,"less",setup3.F.less,setup3.F.less.perc,setup3.FP.less,setup3.FP.less.perc,setup3.FN.less,setup3.FN.less.perc)
  ggbar.df[5,] <- setup3.more.data
  ggbar.df[6,] <- setup3.less.data
}

if(!is.na(setup4)) {
  setup4.more.data <- list(name4,"more",setup4.F.more,setup4.F.more.perc,setup4.FP.more,setup4.FP.more.perc,setup4.FN.more,setup4.FN.more.perc)
  setup4.less.data <- list(name4,"less",setup4.F.less,setup4.F.less.perc,setup4.FP.less,setup4.FP.less.perc,setup4.FN.less,setup4.FN.less.perc)
  ggbar.df[7,] <- setup4.more.data
  ggbar.df[8,] <- setup4.less.data
}

if(!is.na(setup5)) {
  setup5.more.data <- list(name5,"more",setup5.F.more,setup5.F.more.perc,setup5.FP.more,setup5.FP.more.perc,setup5.FN.more,setup5.FN.more.perc)
  setup5.less.data <- list(name5,"less",setup5.F.less,setup5.F.less.perc,setup5.FP.less,setup5.FP.less.perc,setup5.FN.less,setup5.FN.less.perc)
  ggbar.df[9,] <- setup5.more.data
  ggbar.df[10,] <- setup5.less.data
}

if(!is.na(setup6)) {
  setup6.more.data <- list(name6,"more",setup6.F.more,setup6.F.more.perc,setup6.FP.more,setup6.FP.more.perc,setup6.FN.more,setup6.FN.more.perc)
  setup6.less.data <- list(name6,"less",setup6.F.less,setup6.F.less.perc,setup6.FP.less,setup6.FP.less.perc,setup6.FN.less,setup6.FN.less.perc)
  ggbar.df[11,] <- setup6.more.data
  ggbar.df[12,] <- setup6.less.data
}

if(!is.na(setup7)) {
  setup7.more.data <- list(name7,"more",setup7.F.more,setup7.F.more.perc,setup7.FP.more,setup7.FP.more.perc,setup7.FN.more,setup7.FN.more.perc)
  setup7.less.data <- list(name7,"less",setup7.F.less,setup7.F.less.perc,setup7.FP.less,setup7.FP.less.perc,setup7.FN.less,setup7.FN.less.perc)
  ggbar.df[13,] <- setup7.more.data
  ggbar.df[14,] <- setup7.less.data
}

if(!is.na(setup8)) {
  setup8.more.data <- list(name8,"more",setup8.F.more,setup8.F.more.perc,setup8.FP.more,setup8.FP.more.perc,setup8.FN.more,setup8.FN.more.perc)
  setup8.less.data <- list(name8,"less",setup8.F.less,setup8.F.less.perc,setup8.FP.less,setup8.FP.less.perc,setup8.FN.less,setup8.FN.less.perc)
  ggbar.df[15,] <- setup8.more.data
  ggbar.df[16,] <- setup8.less.data
}

ggbar.df[,4] <- round(ggbar.df[,4], digits = 0)
ggbar.df[,6] <- round(ggbar.df[,6], digits = 0)
ggbar.df[,8] <- round(ggbar.df[,8], digits = 0)
if(ncol(ggbar.df)>=10) {
  ggbar.df[,10] <- round(ggbar.df[,10], digits = 0)}

#outline <- rep(100, times=nrow(ggbar.df))
ggbar.df$outline <- rep(100, times=nrow(ggbar.df))

library(plyr)
ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.t.F.sp.perc = 100 - (cumsum(t.F.sp.perc) - (0.5 * t.F.sp.perc)))
ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.t.FP.sp.perc = 100 - (cumsum(t.FP.sp.perc) - (0.5 * t.FP.sp.perc)))
ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.t.FN.sp.perc = 100 - (cumsum(t.FN.sp.perc) - (0.5 * t.FN.sp.perc)))
if(ncol(ggbar.df)>=14) {
  ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.f.F.sp.perc = 100 - (cumsum(f.F.sp.perc) - (0.5 * f.F.sp.perc)))}





### F
ggplot(ggbar.df, aes(x=setup, y=t.F.sp.perc)) +
  geom_bar(data = subset(ggbar.df, compare == "less"), aes(fill = setup), 
           stat = "identity", position = "stack", width = 0.75) +
  #geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
  #         stat = "identity", fill = NA, size = 0.3, color = "black", width = 0.75) +
  geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
           stat = "identity", fill = NA, size = 0.3, color = c("#000000","#0077BB","#AA4499"), width = 0.75) + # Coloured version
  geom_text(data = subset(ggbar.df, compare == "less"), aes(x = setup, y = pos.t.F.sp.perc, label = paste0(t.F.sp.perc,"%")),
            colour="white", family="Calibri", size=4.5, angle = 270) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=17, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=17, family = "Calibri", vjust=2.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        ###
        axis.ticks = element_blank(), 
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x="TSS threshold", y=paste0("Percentage of species with
total false prediction less than ",Fthresh,"%"), fill="xyz") +
  scale_fill_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_color_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_y_continuous(position = "right", expand=c(0.005,0))

ggsave("BIObar_F.png", width = 4.9, height = 11.7, units = "cm", dpi = 800)


### FP
ggplot(ggbar.df, aes(x=setup, y=t.FP.sp.perc)) +
  geom_bar(data = subset(ggbar.df, compare == "less"), aes(fill = setup), 
           stat = "identity", position = "stack", width = 0.75) +
  #geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
  #         stat = "identity", fill = NA, size = 0.3, color = "black", width = 0.75) +
  geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
           stat = "identity", fill = NA, size = 0.3, color = c("#000000","#0077BB","#AA4499"), width = 0.75) + # Coloured version
  geom_text(data = subset(ggbar.df, compare == "less"), aes(x = setup, y = pos.t.FP.sp.perc, label = paste0(t.FP.sp.perc,"%")),
            colour="white", family="Calibri", size=4.5, angle = 270) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=17, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=17, family = "Calibri", vjust=2.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        ###
        axis.ticks = element_blank(), 
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x="TSS threshold", y=paste0("Percentage of species with
false positive prediction less than ",FPthresh,"%"), fill="xyz") +
  scale_fill_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_color_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_y_continuous(position = "right", expand=c(0.005,0))

ggsave("BIObar_FP.png", width = 4.9, height = 11.7, units = "cm", dpi = 800)


### FN
ggplot(ggbar.df, aes(x=setup, y=t.FN.sp.perc)) +
  geom_bar(data = subset(ggbar.df, compare == "less"), aes(fill = setup), 
           stat = "identity", position = "stack", width = 0.75) +
  #geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
  #         stat = "identity", fill = NA, size = 0.3, color = "black", width = 0.75) +
  geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
           stat = "identity", fill = NA, size = 0.3, color = c("#000000","#0077BB","#AA4499"), width = 0.75) + # Coloured version
  geom_text(data = subset(ggbar.df, compare == "less"), aes(x = setup, y = pos.t.FN.sp.perc, label = paste0(t.FN.sp.perc,"%")),
            colour="white", family="Calibri", size=4.5, angle = 270) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=17, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=17, family = "Calibri", vjust=2.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        ###
        axis.ticks = element_blank(), 
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x="TSS threshold", y=paste0("Percentage of species with
false negative prediction less than ",FNthresh,"%"), fill="xyz") +
  scale_fill_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_color_manual(values = c("#000000","#0077BB","#AA4499")) +
  scale_y_continuous(position = "right", expand=c(0.005,0))

ggsave("BIObar_FN.png", width = 4.9, height = 11.7, units = "cm", dpi = 800)

