extrafont::loadfonts(device="win")
extrafont::loadfonts(device="postscript")
library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyr)
library(see)

wd <- "/lustre1/g/sbs_bonebrake/Eugene/Paper1_Vis"  # HPC
wdpc <- "C:/Users/Eugene/Desktop/Paper1_Vis_VIF5"  # PC
wdG15 <- "C:/Users/skywa/Desktop/Paper1_Vis_VIF5"  # Laptop

setwd(wdG15)

options(scipen = 999)

save.filename <- "EM_TSSNA_VIF5_TruncS20" # All untuned algo
save.filename.selectedalgo <- "EM_bmod424_trunc_VIF5_bestalgo_SOUTH_trun20perc" # Selected algo

diff.perc.df <- readRDS(paste0(save.filename,".RData"))


########## Format data for ggplot ##########

# Calculate total raster cells for percentage calculation
#study_area <- terra::rast("proj_TSSNA_Abisara.bifasciata_ensemble_TSSbin.tif")[[1]] # Load any ensemble_TSSbin.tif file generated by SDM
#totalcells <- sum(terra::freq(study_area)[,3])
totalcells <- 125339

# Define the list of items
items <- c("EMca", "EMmean", "EMwmean", "EMmedian")

# Create an empty data frame to store the results
ggplot_columns <- c("Species","setup",
                    "FP","FP.siteperc","FP.rangeperc","FN","FN.siteperc","FN.rangeperc","F","F.siteperc","F.rangeperc")
ggplot.df <- data.frame(matrix(nrow = 0, ncol = length(ggplot_columns)))
colnames(ggplot.df) <- ggplot_columns

# Analysis function
Accuracy_Fun <- function(i, diff.perc.df) { # Pass diff.perc.df as an argument
  sp.data <- diff.perc.df[i, ]
  species <- sp.data$Species
  
  for (item in items) {
    # Construct the column name prefixes
    prefix <- paste0(item, ".") # Handle "All" case
    
    # Extract data based on the current item
    t.FP <- sp.data[[paste0(prefix, "FP")]]
    t.FP.siteperc <- t.FP/totalcells*100
    t.FP.rangeperc <- sp.data[[paste0(prefix, "FP.perc")]]
    t.FN <- sp.data[[paste0(prefix, "FN")]]
    t.FN.siteperc <- t.FN/totalcells*100
    t.FN.rangeperc <- sp.data[[paste0(prefix, "FN.perc")]]
    t.F <- sp.data[[paste0(prefix, "F")]]
    t.F.siteperc <- t.F/totalcells*100
    t.F.rangeperc <- sp.data[[paste0(prefix, "F.perc")]]
    
    # Create the data list
    item.data <- list(species, item, t.FP, t.FP.siteperc, t.FP.rangeperc, 
                      t.FN, t.FN.siteperc, t.FN.rangeperc, t.F, t.F.siteperc, t.F.rangeperc)
    
    # Add the data to the ggplot data frame
    ggplot.df[nrow(ggplot.df) + 1,] <<- item.data
  }
}

# Apply the function to each virtual species
lapply(1:nrow(diff.perc.df), Accuracy_Fun, diff.perc.df = diff.perc.df) 


if (!save.filename.selectedalgo=="NA") {
  full.ggplot.df <- ggplot.df
  
  diff.perc.df <- readRDS(paste0(save.filename.selectedalgo,".RData"))
  
  ggplot.df <- data.frame(matrix(nrow = 0, ncol = length(ggplot_columns)))
  colnames(ggplot.df) <- ggplot_columns
  
  lapply(1:nrow(diff.perc.df), Accuracy_Fun, diff.perc.df = diff.perc.df) 
}


# Write bar plot DF
columns <- c("Item","Metric","Mean","SD","Median")
barplot.df <- data.frame(matrix(nrow = 0, ncol = length(columns))); colnames(barplot.df) <- columns
barplot.siteperc.df <- data.frame(matrix(nrow = 0, ncol = length(columns))); colnames(barplot.siteperc.df) <- columns
barplot.rangeperc.df <- data.frame(matrix(nrow = 0, ncol = length(columns))); colnames(barplot.rangeperc.df) <- columns

# Loop through the items and create subsets and calculate statistics
for (item in items) {
  
  # Create the subset name
  subset_name <- paste0("data.", item)
  
  # Create the subset 
  assign(subset_name, subset(ggplot.df, setup == item))
  
  # Correct item name
  item_name <- item

  # Calculate statistics and add to barplot data frames
  barplot.df[nrow(barplot.df) + 1,] <- list(item_name, "tFP", mean(get(subset_name)$FP), sd(get(subset_name)$FP), median(get(subset_name)$FP))
  barplot.df[nrow(barplot.df) + 1,] <- list(item_name, "tFN", mean(get(subset_name)$FN), sd(get(subset_name)$FN), median(get(subset_name)$FN))
  barplot.siteperc.df[nrow(barplot.siteperc.df) + 1,] <- list(item_name, "tFP.siteperc", mean(get(subset_name)$FP.siteperc), sd(get(subset_name)$FP.siteperc), median(get(subset_name)$FP.siteperc))
  barplot.siteperc.df[nrow(barplot.siteperc.df) + 1,] <- list(item_name, "tFN.siteperc", mean(get(subset_name)$FN.siteperc), sd(get(subset_name)$FN.siteperc), median(get(subset_name)$FN.siteperc))
  barplot.rangeperc.df[nrow(barplot.rangeperc.df) + 1,] <- list(item_name, "tFP.rangeperc", mean(get(subset_name)$FP.rangeperc), sd(get(subset_name)$FP.rangeperc), median(get(subset_name)$FP.rangeperc))
  barplot.rangeperc.df[nrow(barplot.rangeperc.df) + 1,] <- list(item_name, "tFN.rangeperc", mean(get(subset_name)$FN.rangeperc), sd(get(subset_name)$FN.rangeperc), median(get(subset_name)$FN.rangeperc))
}

if (!save.filename.selectedalgo=="NA") {
  # Loop through the items and create subsets and calculate statistics
  for (item in items) {
    
    # Create the subset name
    subset_name <- paste0("data.", item)
    
    # Create the subset 
    assign(subset_name, subset(full.ggplot.df, setup == item))
    
    # Correct item name
    item_name <- paste0(item,"_all_untuned")
    
    # Calculate statistics and add to barplot data frames
    barplot.df[nrow(barplot.df) + 1,] <- list(item_name, "tFP", mean(get(subset_name)$FP), sd(get(subset_name)$FP), median(get(subset_name)$FP))
    barplot.df[nrow(barplot.df) + 1,] <- list(item_name, "tFN", mean(get(subset_name)$FN), sd(get(subset_name)$FN), median(get(subset_name)$FN))
    barplot.siteperc.df[nrow(barplot.siteperc.df) + 1,] <- list(item_name, "tFP.siteperc", mean(get(subset_name)$FP.siteperc), sd(get(subset_name)$FP.siteperc), median(get(subset_name)$FP.siteperc))
    barplot.siteperc.df[nrow(barplot.siteperc.df) + 1,] <- list(item_name, "tFN.siteperc", mean(get(subset_name)$FN.siteperc), sd(get(subset_name)$FN.siteperc), median(get(subset_name)$FN.siteperc))
    barplot.rangeperc.df[nrow(barplot.rangeperc.df) + 1,] <- list(item_name, "tFP.rangeperc", mean(get(subset_name)$FP.rangeperc), sd(get(subset_name)$FP.rangeperc), median(get(subset_name)$FP.rangeperc))
    barplot.rangeperc.df[nrow(barplot.rangeperc.df) + 1,] <- list(item_name, "tFN.rangeperc", mean(get(subset_name)$FN.rangeperc), sd(get(subset_name)$FN.rangeperc), median(get(subset_name)$FN.rangeperc))
  }
}

barplot.df$Metric <- factor(barplot.df$Metric, levels = c("tFP", "tFN"))
barplot.siteperc.df$Metric <- factor(barplot.siteperc.df$Metric, levels = c("tFP.siteperc", "tFN.siteperc"))
barplot.rangeperc.df$Metric <- factor(barplot.rangeperc.df$Metric, levels = c("tFP.rangeperc", "tFN.rangeperc"))

replacement_vector <- c(
  "EMca" = "Committee\naveraging",
  "EMmean" = "Mean",
  "EMwmean" = "Weighted\nmean",
  "EMmedian" = "Median")

if (!save.filename.selectedalgo=="NA") {
  replacement_vector <- c(
    "EMca_all_untuned" = "Committee\naveraging",
    "EMca" = "Committee\naveraging\n(selected algo)",
    "EMmean_all_untuned" = "Mean",
    "EMmean" = "Mean\n(selected algo)",
    "EMwmean_all_untuned" = "Weighted\nmean",
    "EMwmean" = "Weighted\nmean\n(selected algo)",
    "EMmedian_all_untuned" = "Median",
    "EMmedian" = "Median\n(selected algo)")}

barplot.df$Item <- replacement_vector[barplot.df$Item]
barplot.siteperc.df$Item <- replacement_vector[barplot.siteperc.df$Item]
barplot.rangeperc.df$Item <- replacement_vector[barplot.rangeperc.df$Item]

if (!save.filename.selectedalgo == "NA") {
  raw_combined.df <- bind_rows(
    ggplot.df %>% mutate(plot_group = setup),
    full.ggplot.df %>% mutate(plot_group = paste0(setup, "_all_untuned"))
  )
} else {
  raw_combined.df <- ggplot.df %>% mutate(plot_group = setup)
}

item_levels <- names(replacement_vector)

violin_raw.df <- raw_combined.df %>%
  filter(plot_group %in% item_levels) %>%
  mutate(Algo = factor(replacement_vector[plot_group], levels = replacement_vector[item_levels])) %>%
  select(Species, Algo, FP.siteperc, FN.siteperc) %>%
  pivot_longer(cols = c(FP.siteperc, FN.siteperc), names_to = "Metric", values_to = "Value") %>%
  mutate(Metric = factor(Metric, levels = c("FP.siteperc", "FN.siteperc")))

# Set violin fill color
violin_raw.df$FP_ViolinColor <- ifelse(violin_raw.df$Metric == "FP.siteperc", "#A9E5F7", "transparent")
violin_raw.df$FN_ViolinColor <- ifelse(violin_raw.df$Metric == "FN.siteperc", "#D996B7", "transparent")

# Set violin line color
violin_raw.df$FP_LineColor   <- ifelse(violin_raw.df$Metric == "FP.siteperc", "black", "transparent")
violin_raw.df$FN_LineColor   <- ifelse(violin_raw.df$Metric == "FN.siteperc", "black", "transparent")

# Set bar color
violin_raw.df$BarColor       <- ifelse(violin_raw.df$Metric == "FP.siteperc", "#33BBEE", "#882255")

################################################################################
################################################################################

### Format legend item
draw_key_custom_box <- function(data, params, size) {
  fill_val  <- if (!is.null(data$fill)) data$fill else "white"
  alpha_val <- if (!is.null(data$alpha)) data$alpha else 1
  col_val   <- if (!is.null(data$colour)) data$colour else "black"
  lty_val   <- if (!is.null(data$linetype)) data$linetype else 1
  lwd_val   <- if (!is.null(data$linewidth)) data$linewidth else 0.5
  fatten_val <- if (!is.null(params$fatten)) params$fatten else 2.5
  
  # Create box
  box_grob <- rectGrob(
    x = unit(0.5, "npc"), y = unit(0.5, "npc"),
    width = unit(0.5, "npc"), height = unit(0.6, "npc"),
    gp = gpar(
      fill = alpha(fill_val, alpha_val),
      col = col_val,
      lty = lty_val,
      lwd = lwd_val * .pt))
  
  # Create median line
  median_grob <- linesGrob(
    x = unit(c(0.25, 0.75), "npc"),
    y = unit(c(0.5, 0.5), "npc"),
    gp = gpar(
      col = col_val,
      lwd = lwd_val * fatten_val * .pt,
      lineend = "butt"))
  
  grobTree(box_grob, median_grob)
}

### Actual ggplot
ggplot(data = violin_raw.df, aes(x = Algo, y = Value)) + 
  
  # Violin FP (left)
  geom_violinhalf(aes(fill = FP_ViolinColor, color = FP_LineColor), flip = TRUE, 
                  linewidth = 0.4, position = position_nudge(x = 0), width = 1.1) +
  
  # Violin FN (right)
  geom_violinhalf(aes(fill = FN_ViolinColor, color = FN_LineColor), linewidth = 0.4, 
                  position = position_nudge(x = 0), width = 1.1) +
  
  # Boxplot
  stat_summary(aes(fill = BarColor, group = interaction(Algo, BarColor)),
               fun.data = function(x) {
                 stats <- c(
                   ymin   = as.numeric(quantile(x, 0.25)), # Hide whisker
                   lower  = as.numeric(quantile(x, 0.25)),
                   middle = as.numeric(median(x)),
                   upper  = as.numeric(quantile(x, 0.75)),
                   ymax   = as.numeric(quantile(x, 0.75))) # Hide whisker
                 return(stats)},
               geom = "boxplot", position = position_dodge(0.3), width = 0.3,
               color = "black", linewidth = 0.45, fatten = 2.5, # Bold line for median
               key_glyph = draw_key_custom_box) + # Specify custom legend format
  
  # Log transform Y-axis
  scale_y_continuous(trans = "log1p", breaks = c(0, 1, 5, 25, 100)) +
  
  # Set color
  scale_fill_identity(name = " ", breaks = c("#33BBEE", "#882255"), guide = "legend",
                      labels = c("False positive      ", "False negative      ")) +
  scale_color_identity(guide = "none") +
  
  # Line at Y=0
  geom_hline(yintercept = 0, color = "dark grey", linewidth = 0.5) +
  
  # Set theme
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth = 0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0, 0.5, unit = "cm"),
        plot.title    = element_text(size = 22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size = 20, family = "Calibri"),
        axis.title.x  = element_text(size = 19, family = "Calibri", vjust = -1.5),
        axis.title.y  = element_text(size = 19, family = "Calibri", vjust = 2),
        axis.text.x   = element_text(size = 15, family = "Calibri"), 
        axis.text.y   = element_text(size = 15, family = "Calibri"),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.spacing = unit(0.5, "cm"),
        legend.text = element_text(size = 19, family = "Calibri"),
        legend.title = element_text(size = 19, family = "Calibri", margin = margin(b = 25)),
        legend.key.width  = unit(1.1, "cm"), 
        legend.key.height = unit(1.5, "cm")) +
  labs(x = "SDM ensemble method", y = "False prediction percentage (log1p)")

ggsave("EM_best_violin_box_EMca.png", width = 30, height = 18.5, units = "cm", dpi = 800)


