extrafont::loadfonts(device="win")
extrafont::loadfonts(device="postscript")
library(ggplot2)
library(ggpubr)
library(dplyr)

wd <- "/lustre1/g/sbs_bonebrake/Eugene/Paper1_Vis"  # HPC
wdpc <- "C:/Users/Eugene/Desktop/Paper1_Vis"  # PC
wdG15 <- "C:/Users/skywa/Desktop/Paper1_Vis"  # Laptop

setwd(wdG15)

options(scipen = 999)

#save.filename <- "EM_bmod424_PCvspEMmean_trunc_rev_SOUTH_trun20perc" # All untuned algo
#save.filename.selectedalgo <- "EM_bmod424_PCvspEMmean_trunc_rev_best4algo2_SOUTH_trun20perc" # Selected untuned algo

save.filename.selectedalgo <- "NA" # Selected untuned algo

save.filename <- "EM_bmod424_trunc_rev_SOUTH_trun20perc" # All untuned algo
save.filename.selectedalgo <- "EM_bmod424_trunc_rev_bestalgo_SOUTH_trun20perc" # Selected untuned algo
#save.filename.selectedalgo <- "EM_bmod424_trunc_rev_best3algo_SOUTH_trun20perc" # Selected untuned algo


diff.perc.df <- readRDS(paste0(save.filename,".RData"))


########## Format data for ggplot ##########

# Calculate total raster cells for percentage calculation
study_area <- terra::rast("proj_TSSNA_Abisara.bifasciata_ensemble_TSSbin.tif")[[1]] # Load any ensemble_TSSbin.tif file generated by SDM
totalcells <- sum(terra::freq(study_area)[,3])

# Define the list of items
items <- c("EMca", "EMmean", "EMwmean", "EMmedian")

# Create an empty data frame to store the results
ggplot_columns <- c("Species","setup",
                    "FP","FP.siteperc","FP.rangeperc","FN","FN.siteperc","FN.rangeperc","F","F.siteperc","F.rangeperc")
ggplot.df <- data.frame(matrix(nrow = 0, ncol = length(ggplot_columns)))
colnames(ggplot.df) <- ggplot_columns

# Analysis function
Accuracy_Fun <- function(i, diff.perc.df) { # Pass diff.perc.df as an argument
  sp.data <- diff.perc.df[i, ]
  species <- sp.data$Species
  
  for (item in items) {
    # Construct the column name prefixes
    prefix <- paste0(item, ".") # Handle "All" case
    
    # Extract data based on the current item
    t.FP <- sp.data[[paste0(prefix, "FP")]]
    t.FP.siteperc <- t.FP/totalcells*100
    t.FP.rangeperc <- sp.data[[paste0(prefix, "FP.perc")]]
    t.FN <- sp.data[[paste0(prefix, "FN")]]
    t.FN.siteperc <- t.FN/totalcells*100
    t.FN.rangeperc <- sp.data[[paste0(prefix, "FN.perc")]]
    t.F <- sp.data[[paste0(prefix, "F")]]
    t.F.siteperc <- t.F/totalcells*100
    t.F.rangeperc <- sp.data[[paste0(prefix, "F.perc")]]
    
    # Create the data list
    item.data <- list(species, item, t.FP, t.FP.siteperc, t.FP.rangeperc, 
                      t.FN, t.FN.siteperc, t.FN.rangeperc, t.F, t.F.siteperc, t.F.rangeperc)
    
    # Add the data to the ggplot data frame
    ggplot.df[nrow(ggplot.df) + 1,] <<- item.data
  }
}

# Apply the function to each virtual species
lapply(1:nrow(diff.perc.df), Accuracy_Fun, diff.perc.df = diff.perc.df) 


###### Count results ######

### False 

Fplot <- ggplot(ggplot.df) + 
  stat_density(aes(x=F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  #stat_density(aes(x=t.F, colour=setup), geom="line", linetype=5, position="identity", size=0.55) +
  #stat_density(aes(x=f.F, colour=setup), geom="line", position="identity", size=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false predictions (%)", y = "Density", fill="xyz") +
  scale_color_manual(values=c("#999933","#0077BB","#AA4499","#33BBEE")) +
  scale_x_continuous(limits = c(-1.8,17),expand=c(0,0), breaks = seq(0,15,5)) #+
  #scale_y_continuous(expand=c(0.025,0)) # c(a,b): a=relative expansion(%) b=absolute expansion


### False positive 

FPplot <- ggplot(ggplot.df) + 
  stat_density(aes(x=FP.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  #stat_density(aes(x=t.F, colour=setup), geom="line", linetype=5, position="identity", size=0.55) +
  #stat_density(aes(x=f.F, colour=setup), geom="line", position="identity", size=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "False positive predictions (%)", y = "Density", fill="xyz") +
  scale_color_manual(values=c("#999933","#0077BB","#AA4499","#33BBEE")) +
  scale_x_continuous(limits = c(-1.6,13),expand=c(0,0), breaks = seq(0,12,4)) #+
#scale_y_continuous(expand=c(0.025,0)) # c(a,b): a=relative expansion(%) b=absolute expansion


### False negative 

FNplot <- ggplot(ggplot.df) + 
  stat_density(aes(x=FN.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  #stat_density(aes(x=t.F, colour=setup), geom="line", linetype=5, position="identity", size=0.55) +
  #stat_density(aes(x=f.F, colour=setup), geom="line", position="identity", size=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "False negative predictions (%)", y = "Density", fill="xyz") +
  scale_color_manual(values=c("#999933","#0077BB","#AA4499","#33BBEE")) +
  scale_x_continuous(limits = c(-1.1,6.5),expand=c(0,0), breaks = seq(0,6,2)) #+
#scale_y_continuous(expand=c(0.025,0)) # c(a,b): a=relative expansion(%) b=absolute expansion


ggarrange(Fplot, FPplot, FNplot,
          nrow = 3, ncol = 1, align = "v")

ggsave("EM.png", width = 24.5, height = 35, units = "cm", dpi = 1000)




###### Legend ######
ggplot(ggplot.df) + 
  stat_density(aes(x=FN.perc, colour=setup), geom="line", position="identity", size=6) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
        axis.title.y  = element_blank(),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        legend.key = element_blank(),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.text = element_text(size = 14, family = "Calibri"),
        legend.title = element_text(size = 14, family = "Calibri"
                                    # , margin = margin(b=20)
        ),
        legend.key.width = unit(1,"cm"),
        legend.key.spacing.x = unit(0.5,'cm')) +
  labs(y = "Density", x = "False predictions", fill="xyz") +
  guides(color = guide_legend(title = "Ensemble algorithm      ")) +
  scale_color_manual(values=c("#999933","#0077BB","#AA4499","#33BBEE"), 
                     labels=c("Committee averaging","Mean","Median","Weighted mean"))

ggsave("EM_legend.png", width = 26, height = 12, units = "cm", dpi = 1200)











###### Bar plot ######

#Fthresh <- 5000
#FPthresh <- 3000
#FNthresh <- 1500

##OR##

Fpercthresh <- 3
FPpercthresh <- 2.5
FNpercthresh <- 1

Fthresh <- totalcells*Fpercthresh/100
FPthresh <- totalcells*FPpercthresh/100
FNthresh <- totalcells*FNpercthresh/100

### Create new DF 
columns <- c("setup","compare","t.F.sp","t.F.sp.perc","t.FP.sp","t.FP.sp.perc","t.FN.sp","t.FN.sp.perc")
ggbar.df <- data.frame(matrix(nrow = 0, ncol = length(columns))) 
colnames(ggbar.df) <- columns

### Specify names
setup1 <- "EMca"
name1 <- "EMca"
setup2 <- "EMmean"
name2 <- "EMmean"
setup3 <- "EMwmean"
name3 <- "EMwmean"
setup4 <- "EMmedian"
name4 <- "EMmedian"

### Get data
if(!is.na(setup1)) {
  setup1.F.more <- length(diff.perc.df[[paste0(setup1, ".F")]][diff.perc.df[[paste0(setup1, ".F")]] >= Fthresh])
  setup1.F.more.perc <- setup1.F.more / length(diff.perc.df[[paste0(setup1, ".F")]])*100
  setup1.F.less <- length(diff.perc.df[[paste0(setup1, ".F")]][diff.perc.df[[paste0(setup1, ".F")]] < Fthresh])
  setup1.F.less.perc <- setup1.F.less / length(diff.perc.df[[paste0(setup1, ".F")]])*100
  
  setup1.FP.more <- length(diff.perc.df[[paste0(setup1, ".FP")]][diff.perc.df[[paste0(setup1, ".FP")]] >= FPthresh])
  setup1.FP.more.perc <- setup1.FP.more / length(diff.perc.df[[paste0(setup1, ".FP")]])*100
  setup1.FP.less <- length(diff.perc.df[[paste0(setup1, ".FP")]][diff.perc.df[[paste0(setup1, ".FP")]] < FPthresh])
  setup1.FP.less.perc <- setup1.FP.less / length(diff.perc.df[[paste0(setup1, ".FP")]])*100
  
  setup1.FN.more <- length(diff.perc.df[[paste0(setup1, ".FN")]][diff.perc.df[[paste0(setup1, ".FN")]] >= FNthresh])
  setup1.FN.more.perc <- setup1.FN.more / length(diff.perc.df[[paste0(setup1, ".FN")]])*100
  setup1.FN.less <- length(diff.perc.df[[paste0(setup1, ".FN")]][diff.perc.df[[paste0(setup1, ".FN")]] < FNthresh])
  setup1.FN.less.perc <- setup1.FN.less / length(diff.perc.df[[paste0(setup1, ".FN")]])*100
} 

if(!is.na(setup2)) {
  setup2.F.more <- length(diff.perc.df[[paste0(setup2, ".F")]][diff.perc.df[[paste0(setup2, ".F")]] >= Fthresh])
  setup2.F.more.perc <- setup2.F.more / length(diff.perc.df[[paste0(setup2, ".F")]])*100
  setup2.F.less <- length(diff.perc.df[[paste0(setup2, ".F")]][diff.perc.df[[paste0(setup2, ".F")]] < Fthresh])
  setup2.F.less.perc <- setup2.F.less / length(diff.perc.df[[paste0(setup2, ".F")]])*100
  
  setup2.FP.more <- length(diff.perc.df[[paste0(setup2, ".FP")]][diff.perc.df[[paste0(setup2, ".FP")]] >= FPthresh])
  setup2.FP.more.perc <- setup2.FP.more / length(diff.perc.df[[paste0(setup2, ".FP")]])*100
  setup2.FP.less <- length(diff.perc.df[[paste0(setup2, ".FP")]][diff.perc.df[[paste0(setup2, ".FP")]] < FPthresh])
  setup2.FP.less.perc <- setup2.FP.less / length(diff.perc.df[[paste0(setup2, ".FP")]])*100
  
  setup2.FN.more <- length(diff.perc.df[[paste0(setup2, ".FN")]][diff.perc.df[[paste0(setup2, ".FN")]] >= FNthresh])
  setup2.FN.more.perc <- setup2.FN.more / length(diff.perc.df[[paste0(setup2, ".FN")]])*100
  setup2.FN.less <- length(diff.perc.df[[paste0(setup2, ".FN")]][diff.perc.df[[paste0(setup2, ".FN")]] < FNthresh])
  setup2.FN.less.perc <- setup2.FN.less / length(diff.perc.df[[paste0(setup2, ".FN")]])*100
}

if(!is.na(setup3)) {
  setup3.F.more <- length(diff.perc.df[[paste0(setup3, ".F")]][diff.perc.df[[paste0(setup3, ".F")]] >= Fthresh])
  setup3.F.more.perc <- setup3.F.more / length(diff.perc.df[[paste0(setup3, ".F")]])*100
  setup3.F.less <- length(diff.perc.df[[paste0(setup3, ".F")]][diff.perc.df[[paste0(setup3, ".F")]] < Fthresh])
  setup3.F.less.perc <- setup3.F.less / length(diff.perc.df[[paste0(setup3, ".F")]])*100
  
  setup3.FP.more <- length(diff.perc.df[[paste0(setup3, ".FP")]][diff.perc.df[[paste0(setup3, ".FP")]] >= FPthresh])
  setup3.FP.more.perc <- setup3.FP.more / length(diff.perc.df[[paste0(setup3, ".FP")]])*100
  setup3.FP.less <- length(diff.perc.df[[paste0(setup3, ".FP")]][diff.perc.df[[paste0(setup3, ".FP")]] < FPthresh])
  setup3.FP.less.perc <- setup3.FP.less / length(diff.perc.df[[paste0(setup3, ".FP")]])*100
  
  setup3.FN.more <- length(diff.perc.df[[paste0(setup3, ".FN")]][diff.perc.df[[paste0(setup3, ".FN")]] >= FNthresh])
  setup3.FN.more.perc <- setup3.FN.more / length(diff.perc.df[[paste0(setup3, ".FN")]])*100
  setup3.FN.less <- length(diff.perc.df[[paste0(setup3, ".FN")]][diff.perc.df[[paste0(setup3, ".FN")]] < FNthresh])
  setup3.FN.less.perc <- setup3.FN.less / length(diff.perc.df[[paste0(setup3, ".FN")]])*100
}

if(!is.na(setup4)) {
  setup4.F.more <- length(diff.perc.df[[paste0(setup4, ".F")]][diff.perc.df[[paste0(setup4, ".F")]] >= Fthresh])
  setup4.F.more.perc <- setup4.F.more / length(diff.perc.df[[paste0(setup4, ".F")]])*100
  setup4.F.less <- length(diff.perc.df[[paste0(setup4, ".F")]][diff.perc.df[[paste0(setup4, ".F")]] < Fthresh])
  setup4.F.less.perc <- setup4.F.less / length(diff.perc.df[[paste0(setup4, ".F")]])*100
  
  setup4.FP.more <- length(diff.perc.df[[paste0(setup4, ".FP")]][diff.perc.df[[paste0(setup4, ".FP")]] >= FPthresh])
  setup4.FP.more.perc <- setup4.FP.more / length(diff.perc.df[[paste0(setup4, ".FP")]])*100
  setup4.FP.less <- length(diff.perc.df[[paste0(setup4, ".FP")]][diff.perc.df[[paste0(setup4, ".FP")]] < FPthresh])
  setup4.FP.less.perc <- setup4.FP.less / length(diff.perc.df[[paste0(setup4, ".FP")]])*100
  
  setup4.FN.more <- length(diff.perc.df[[paste0(setup4, ".FN")]][diff.perc.df[[paste0(setup4, ".FN")]] >= FNthresh])
  setup4.FN.more.perc <- setup4.FN.more / length(diff.perc.df[[paste0(setup4, ".FN")]])*100
  setup4.FN.less <- length(diff.perc.df[[paste0(setup4, ".FN")]][diff.perc.df[[paste0(setup4, ".FN")]] < FNthresh])
  setup4.FN.less.perc <- setup4.FN.less / length(diff.perc.df[[paste0(setup4, ".FN")]])*100
}


### Write data
if(!is.na(setup1)) {
  setup1.more.data <- list(name1,"more",setup1.F.more,setup1.F.more.perc,setup1.FP.more,setup1.FP.more.perc,setup1.FN.more,setup1.FN.more.perc)
  setup1.less.data <- list(name1,"less",setup1.F.less,setup1.F.less.perc,setup1.FP.less,setup1.FP.less.perc,setup1.FN.less,setup1.FN.less.perc)
  ggbar.df[1,] <- setup1.more.data
  ggbar.df[2,] <- setup1.less.data
}

if(!is.na(setup2)) {
  setup2.more.data <- list(name2,"more",setup2.F.more,setup2.F.more.perc,setup2.FP.more,setup2.FP.more.perc,setup2.FN.more,setup2.FN.more.perc)
  setup2.less.data <- list(name2,"less",setup2.F.less,setup2.F.less.perc,setup2.FP.less,setup2.FP.less.perc,setup2.FN.less,setup2.FN.less.perc)
  ggbar.df[3,] <- setup2.more.data
  ggbar.df[4,] <- setup2.less.data
}

if(!is.na(setup3)) {
  setup3.more.data <- list(name3,"more",setup3.F.more,setup3.F.more.perc,setup3.FP.more,setup3.FP.more.perc,setup3.FN.more,setup3.FN.more.perc)
  setup3.less.data <- list(name3,"less",setup3.F.less,setup3.F.less.perc,setup3.FP.less,setup3.FP.less.perc,setup3.FN.less,setup3.FN.less.perc)
  ggbar.df[5,] <- setup3.more.data
  ggbar.df[6,] <- setup3.less.data
}

if(!is.na(setup4)) {
  setup4.more.data <- list(name4,"more",setup4.F.more,setup4.F.more.perc,setup4.FP.more,setup4.FP.more.perc,setup4.FN.more,setup4.FN.more.perc)
  setup4.less.data <- list(name4,"less",setup4.F.less,setup4.F.less.perc,setup4.FP.less,setup4.FP.less.perc,setup4.FN.less,setup4.FN.less.perc)
  ggbar.df[7,] <- setup4.more.data
  ggbar.df[8,] <- setup4.less.data
}


ggbar.df[,4] <- round(ggbar.df[,4], digits = 0)
ggbar.df[,6] <- round(ggbar.df[,6], digits = 0)
ggbar.df[,8] <- round(ggbar.df[,8], digits = 0)
if(ncol(ggbar.df)>=10) {
  ggbar.df[,10] <- round(ggbar.df[,10], digits = 0)}

#outline <- rep(100, times=nrow(ggbar.df))
ggbar.df$outline <- rep(100, times=nrow(ggbar.df))

library(plyr)
ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.t.F.sp.perc = 100 - (cumsum(t.F.sp.perc) - (0.5 * t.F.sp.perc)))
ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.t.FP.sp.perc = 100 - (cumsum(t.FP.sp.perc) - (0.5 * t.FP.sp.perc)))
ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.t.FN.sp.perc = 100 - (cumsum(t.FN.sp.perc) - (0.5 * t.FN.sp.perc)))
if(ncol(ggbar.df)>=14) {
  ggbar.df <- ddply(ggbar.df, .(setup), transform, pos.f.F.sp.perc = 100 - (cumsum(f.F.sp.perc) - (0.5 * f.F.sp.perc)))}





### F
ggplot(ggbar.df, aes(x=setup, y=t.F.sp.perc)) +
  geom_bar(data = subset(ggbar.df, compare == "less"), aes(fill = setup), 
           stat = "identity", position = "stack", width = 0.75) +
  #geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
  #         stat = "identity", fill = NA, size = 0.3, color = "black", width = 0.75) +
  geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
           stat = "identity", fill = NA, size = 0.3, color = c("#999933","#0077BB","#AA4499","#33BBEE"), width = 0.75) + # Coloured version
  geom_text(data = subset(ggbar.df, compare == "less"), aes(x = setup, y = pos.t.F.sp.perc, label = paste0(t.F.sp.perc,"%")),
            colour="white", family="Calibri", size=4.5, angle = 270) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=2.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        ###
        axis.ticks = element_blank(), 
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(y=paste0("Percentage of species with less 
than ",Fpercthresh,"% total false prediction"), fill="xyz") +
  scale_fill_manual(values = c("#999933","#0077BB","#AA4499","#33BBEE")) +
  scale_color_manual(values = c("#999933","#0077BB","#AA4499","#33BBEE")) +
  scale_y_continuous(position = "right", expand=c(0.005,0))

ggsave("EMbar_F.png", width = 5.65, height = 11.7, units = "cm", dpi = 800)


### FP
ggplot(ggbar.df, aes(x=setup, y=t.FP.sp.perc)) +
  geom_bar(data = subset(ggbar.df, compare == "less"), aes(fill = setup), 
           stat = "identity", position = "stack", width = 0.75) +
  #geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
  #         stat = "identity", fill = NA, size = 0.3, color = "black", width = 0.75) +
  geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
           stat = "identity", fill = NA, size = 0.3, color = c("#999933","#0077BB","#AA4499","#33BBEE"), width = 0.75) + # Coloured version
  geom_text(data = subset(ggbar.df, compare == "less"), aes(x = setup, y = pos.t.FP.sp.perc, label = paste0(t.FP.sp.perc,"%")),
            colour="white", family="Calibri", size=4.5, angle = 270) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=2.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        ###
        axis.ticks = element_blank(), 
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(y=paste0("Percentage of species with less
than ",FPpercthresh,"% false positive prediction"), fill="xyz") +
  scale_fill_manual(values = c("#999933","#0077BB","#AA4499","#33BBEE")) +
  scale_color_manual(values = c("#999933","#0077BB","#AA4499","#33BBEE")) +
  scale_y_continuous(position = "right", expand=c(0.005,0))

ggsave("EMbar_FP.png", width = 5.65, height = 11.7, units = "cm", dpi = 800)


### FN
ggplot(ggbar.df, aes(x=setup, y=t.FN.sp.perc)) +
  geom_bar(data = subset(ggbar.df, compare == "less"), aes(fill = setup), 
           stat = "identity", position = "stack", width = 0.75) +
  #geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
  #         stat = "identity", fill = NA, size = 0.3, color = "black", width = 0.75) +
  geom_bar(data = subset(ggbar.df, compare == "more"), aes(y = outline, color = setup), 
           stat = "identity", fill = NA, size = 0.3, color = c("#999933","#0077BB","#AA4499","#33BBEE"), width = 0.75) + # Coloured version
  geom_text(data = subset(ggbar.df, compare == "less"), aes(x = setup, y = pos.t.FN.sp.perc, label = paste0(t.FN.sp.perc,"%")),
            colour="white", family="Calibri", size=4.5, angle = 270) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=22, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=20, family = "Calibri"),
        axis.title.x  = element_text(size=19, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=19, family = "Calibri", vjust=2.5),
        axis.text.x   = element_text(size=12.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        ###
        axis.ticks = element_blank(), 
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(y=paste0("Percentage of species with less
than ",FNpercthresh,"% false negative prediction"), fill="xyz") +
  scale_fill_manual(values = c("#999933","#0077BB","#AA4499","#33BBEE")) +
  scale_color_manual(values = c("#999933","#0077BB","#AA4499","#33BBEE")) +
  scale_y_continuous(position = "right", expand=c(0.005,0))

ggsave("EMbar_FN.png", width = 5.65, height = 11.7, units = "cm", dpi = 800)


