###### Replaced by FPFN barplot ######

extrafont::loadfonts(device="win")
extrafont::loadfonts(device="postscript")
library(ggplot2)
library(ggpubr)
library(dplyr)

wd <- "/lustre1/g/sbs_bonebrake/Eugene/Paper1_Vis"  # HPC
wdpc <- "C:/Users/Eugene/Desktop/Paper1_Vis"  # PC
wdG15 <- "C:/Users/skywa/Desktop/Paper1_Vis"  # Laptop

setwd(wdG15)

options(scipen = 999)

save.filename <- "Algo_REV_EMca_proj_TSSNA" # Name the df output file

diff.perc.df <- readRDS(paste0(save.filename,".RData"))


########## Format data for ggplot ##########

# Calculate total raster cells for percentage calculation
study_area <- terra::rast("proj_TSSNA_Abisara.bifasciata_ensemble_TSSbin.tif")[[1]] # Load any ensemble_TSSbin.tif file generated by SDM
totalcells <- sum(terra::freq(study_area)[,3])

# Define the list of algorithms
algorithms <- c("All", "ANN", "CTA", "GBM", "GLM", "MARS", "MAXNET", "RF", "XGBOOST",
                "tuned_ANN", "tuned_CTA", "tuned_GBM", "tuned_GLM",
                "tuned_MARS", "tuned_RF")


# Create an empty data frame to store the results
ggplot_columns <- c("Species","setup",
                    "f.FP","f.FP.siteperc","f.FP.rangeperc","f.FN","f.FN.siteperc","f.FN.rangeperc","f.F","f.F.siteperc","f.F.rangeperc",
                    "t.FP","t.FP.siteperc","t.FP.rangeperc","t.FN","t.FN.siteperc","t.FN.rangeperc","t.F","t.F.siteperc","t.F.rangeperc")
ggplot.df <- data.frame(matrix(nrow = 0, ncol = length(ggplot_columns)))
colnames(ggplot.df) <- ggplot_columns

# Analysis function
Accuracy_Fun <- function(i, diff.perc.df) { # Pass diff.perc.df as an argument
  sp.data <- diff.perc.df[i, ]
  species <- sp.data$Species
  
  for (algorithm in algorithms) {
    # Construct the column name prefixes
    prefix <- paste0(algorithm, ".") # Handle "All" case
    
    # Extract data based on the current algorithm
    f.FP <- sp.data[[paste0(prefix, "f.FP")]]
    f.FP.siteperc <- f.FP/totalcells*100
    f.FP.rangeperc <- sp.data[[paste0(prefix, "f.FP.perc")]]
    f.FN <- sp.data[[paste0(prefix, "f.FN")]]
    f.FN.siteperc <- f.FN/totalcells*100
    f.FN.rangeperc <- sp.data[[paste0(prefix, "f.FN.perc")]]
    f.F <- sp.data[[paste0(prefix, "f.F")]]
    f.F.siteperc <- f.F/totalcells*100
    f.F.rangeperc <- sp.data[[paste0(prefix, "f.F.perc")]]
    
    t.FP <- sp.data[[paste0(prefix, "t.FP")]]
    t.FP.siteperc <- t.FP/totalcells*100
    t.FP.rangeperc <- sp.data[[paste0(prefix, "t.FP.perc")]]
    t.FN <- sp.data[[paste0(prefix, "t.FN")]]
    t.FN.siteperc <- t.FN/totalcells*100
    t.FN.rangeperc <- sp.data[[paste0(prefix, "t.FN.perc")]]
    t.F <- sp.data[[paste0(prefix, "t.F")]]
    t.F.siteperc <- t.F/totalcells*100
    t.F.rangeperc <- sp.data[[paste0(prefix, "t.F.perc")]]
    
    # Create the data list
    algorithm.data <- list(species, algorithm, 
                           f.FP, f.FP.siteperc, f.FP.rangeperc, f.FN, f.FN.siteperc, f.FN.rangeperc, f.F, f.F.siteperc, f.F.rangeperc,
                           t.FP, t.FP.siteperc, t.FP.rangeperc, t.FN, t.FN.siteperc, t.FN.rangeperc, t.F, t.F.siteperc, t.F.rangeperc)
    
    # Add the data to the ggplot data frame
    ggplot.df[nrow(ggplot.df) + 1,] <<- algorithm.data
  }
}

# Apply the function to each virtual species
lapply(1:nrow(diff.perc.df), Accuracy_Fun, diff.perc.df = diff.perc.df) # Pass diff.perc.df








###### Tuned algo results ######

#algo_list <- c("All", "ANN", "CTA", "GBM", "GLM", "MARS", "MAXNET", "RF", "XGBOOST")
#algoname_list <- c("All", "ANN", "CTA", "GBM", "GLM", "MARS", "MaxEnt", "RF", "XGBoost")

algo_list <- c("ANN", "CTA", "GBM", "GLM", "MARS", "MAXNET", "RF", "XGBOOST")
algoname_list <- c("ANN", "CTA", "GBM", "GLM", "MARS", "MaxEnt", "RF", "XGBoost")




algo <- algo_list[1]
algoname <- algoname_list[1]

ggplot.algo.df <- subset(ggplot.df, setup == algo)
ggplot.algo.df$setup <- "A"

if (paste0("tuned_",algo) %in% algorithms) {
  df <- subset(ggplot.df, setup == paste0("tuned_",algo))
  df$setup <- "B"
  ggplot.algo.df <- rbind(ggplot.algo.df,df)
}

algoplot1 <- ggplot(ggplot.algo.df) + 
  stat_density(aes(x=f.F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  stat_density(aes(x=t.F.siteperc, colour=setup), geom="line", linetype=5, position="identity", linewidth=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=26, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=23, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=21, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=21, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false prediction (%)", y = "Density", title = paste(algoname), fill="xyz") +
  scale_color_manual(values=c(A="#332288",B="#88CCEE")) + # "#33BBEE"
  scale_x_continuous(limits = c(-2.5,18.5), expand=c(0,0), breaks = seq(0,15,5)) +
  scale_y_continuous(limits = c(0,0.28), expand=c(0,0))

###

algo <- algo_list[2]
algoname <- algoname_list[2]

ggplot.algo.df <- subset(ggplot.df, setup == algo)
ggplot.algo.df$setup <- "A"

if (paste0("tuned_",algo) %in% algorithms) {
  df <- subset(ggplot.df, setup == paste0("tuned_",algo))
  df$setup <- "B"
  ggplot.algo.df <- rbind(ggplot.algo.df,df)
}

algoplot2 <- ggplot(ggplot.algo.df) + 
  stat_density(aes(x=f.F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  stat_density(aes(x=t.F.siteperc, colour=setup), geom="line", linetype=5, position="identity", linewidth=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=26, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=23, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=21, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=21, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false prediction (%)", y = "Density", title = paste(algoname), fill="xyz") +
  scale_color_manual(values=c(A="#332288",B="#88CCEE")) + # "#33BBEE"
  scale_x_continuous(limits = c(-2.5,18.5), expand=c(0,0), breaks = seq(0,15,5)) +
  scale_y_continuous(limits = c(0,0.28), expand=c(0,0))

###

algo <- algo_list[3]
algoname <- algoname_list[3]

ggplot.algo.df <- subset(ggplot.df, setup == algo)
ggplot.algo.df$setup <- "A"

if (paste0("tuned_",algo) %in% algorithms) {
  df <- subset(ggplot.df, setup == paste0("tuned_",algo))
  df$setup <- "B"
  ggplot.algo.df <- rbind(ggplot.algo.df,df)
}

algoplot3 <- ggplot(ggplot.algo.df) + 
  stat_density(aes(x=f.F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  stat_density(aes(x=t.F.siteperc, colour=setup), geom="line", linetype=5, position="identity", linewidth=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=26, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=23, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=21, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=21, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false prediction (%)", y = "Density", title = paste(algoname), fill="xyz") +
  scale_color_manual(values=c(A="#332288",B="#88CCEE")) + # "#33BBEE"
  scale_x_continuous(limits = c(-2.5,18.5), expand=c(0,0), breaks = seq(0,15,5)) +
  scale_y_continuous(limits = c(0,0.28), expand=c(0,0))

###

algo <- algo_list[4]
algoname <- algoname_list[4]

ggplot.algo.df <- subset(ggplot.df, setup == algo)
ggplot.algo.df$setup <- "A"

if (paste0("tuned_",algo) %in% algorithms) {
  df <- subset(ggplot.df, setup == paste0("tuned_",algo))
  df$setup <- "B"
  ggplot.algo.df <- rbind(ggplot.algo.df,df)
}

algoplot4 <- ggplot(ggplot.algo.df) + 
  stat_density(aes(x=f.F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  stat_density(aes(x=t.F.siteperc, colour=setup), geom="line", linetype=5, position="identity", linewidth=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=26, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=23, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=21, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=21, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false prediction (%)", y = "Density", title = paste(algoname), fill="xyz") +
  scale_color_manual(values=c(A="#332288",B="#88CCEE")) + # "#33BBEE"
  scale_x_continuous(limits = c(-2.5,18.5), expand=c(0,0), breaks = seq(0,15,5)) +
  scale_y_continuous(limits = c(0,0.28), expand=c(0,0))

###

algo <- algo_list[5]
algoname <- algoname_list[5]

ggplot.algo.df <- subset(ggplot.df, setup == algo)
ggplot.algo.df$setup <- "A"

if (paste0("tuned_",algo) %in% algorithms) {
  df <- subset(ggplot.df, setup == paste0("tuned_",algo))
  df$setup <- "B"
  ggplot.algo.df <- rbind(ggplot.algo.df,df)
}

algoplot5 <- ggplot(ggplot.algo.df) + 
  stat_density(aes(x=f.F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  stat_density(aes(x=t.F.siteperc, colour=setup), geom="line", linetype=5, position="identity", linewidth=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=26, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=23, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=21, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=21, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false prediction (%)", y = "Density", title = paste(algoname), fill="xyz") +
  scale_color_manual(values=c(A="#332288",B="#88CCEE")) + # "#33BBEE"
  scale_x_continuous(limits = c(-2.5,18.5), expand=c(0,0), breaks = seq(0,15,5)) +
  scale_y_continuous(limits = c(0,0.28), expand=c(0,0))

###

algo <- algo_list[6]
algoname <- algoname_list[6]

ggplot.algo.df <- subset(ggplot.df, setup == algo)
ggplot.algo.df$setup <- "A"

if (paste0("tuned_",algo) %in% algorithms) {
  df <- subset(ggplot.df, setup == paste0("tuned_",algo))
  df$setup <- "B"
  ggplot.algo.df <- rbind(ggplot.algo.df,df)
}

algoplot6 <- ggplot(ggplot.algo.df) + 
  stat_density(aes(x=f.F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  stat_density(aes(x=t.F.siteperc, colour=setup), geom="line", linetype=5, position="identity", linewidth=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=26, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=23, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=21, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=21, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false prediction (%)", y = "Density", title = paste(algoname), fill="xyz") +
  scale_color_manual(values=c(A="#332288",B="#88CCEE")) + # "#33BBEE"
  scale_x_continuous(limits = c(-2.5,18.5), expand=c(0,0), breaks = seq(0,15,5)) +
  scale_y_continuous(limits = c(0,0.28), expand=c(0,0))

###

algo <- algo_list[7]
algoname <- algoname_list[7]

ggplot.algo.df <- subset(ggplot.df, setup == algo)
ggplot.algo.df$setup <- "A"

if (paste0("tuned_",algo) %in% algorithms) {
  df <- subset(ggplot.df, setup == paste0("tuned_",algo))
  df$setup <- "B"
  ggplot.algo.df <- rbind(ggplot.algo.df,df)
}

algoplot7 <- ggplot(ggplot.algo.df) + 
  stat_density(aes(x=f.F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  stat_density(aes(x=t.F.siteperc, colour=setup), geom="line", linetype=5, position="identity", linewidth=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=26, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=23, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=21, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=21, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false prediction (%)", y = "Density", title = paste(algoname), fill="xyz") +
  scale_color_manual(values=c(A="#332288",B="#88CCEE")) + # "#33BBEE"
  scale_x_continuous(limits = c(-2.5,18.5), expand=c(0,0), breaks = seq(0,15,5)) +
  scale_y_continuous(limits = c(0,0.28), expand=c(0,0))

###

algo <- algo_list[8]
algoname <- algoname_list[8]

ggplot.algo.df <- subset(ggplot.df, setup == algo)
ggplot.algo.df$setup <- "A"

if (paste0("tuned_",algo) %in% algorithms) {
  df <- subset(ggplot.df, setup == paste0("tuned_",algo))
  df$setup <- "B"
  ggplot.algo.df <- rbind(ggplot.algo.df,df)
}

algoplot8 <- ggplot(ggplot.algo.df) + 
  stat_density(aes(x=f.F.siteperc, colour=setup), geom="line", position="identity", linewidth=0.55) +
  stat_density(aes(x=t.F.siteperc, colour=setup), geom="line", linetype=5, position="identity", linewidth=0.55) +
  geom_hline(yintercept = 0, color = "dark grey", linewidth=0.5) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA, linewidth=0.7),
        ###
        plot.margin = margin(0.5, 0.5, 0.6, 0.5, unit = "cm"),
        plot.title    = element_text(size=26, family = "Calibri", face = "bold", hjust = 0.5, vjust = 1),
        plot.subtitle = element_text(size=23, family = "Calibri"),
        ###
        axis.title.x  = element_text(size=21, family = "Calibri", vjust=-0.3),
        axis.title.y  = element_text(size=21, family = "Calibri", vjust=1.5),
        axis.text.x   = element_text(size=15.5, family = "Calibri"),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        ###
        axis.ticks = element_line(linewidth = 0.6) , 
        axis.ticks.length = unit(0.2, "cm"),
        ###
        legend.key = element_blank(),
        legend.text = element_blank(),
        legend.title = element_blank(),
        legend.position = "none") +
  labs(x = "Total false prediction (%)", y = "Density", title = paste(algoname), fill="xyz") +
  scale_color_manual(values=c(A="#332288",B="#88CCEE")) + # "#33BBEE"
  scale_x_continuous(limits = c(-2.5,18.5), expand=c(0,0), breaks = seq(0,15,5)) +
  scale_y_continuous(limits = c(0,0.28), expand=c(0,0))


ggarrange(algoplot1, algoplot2, algoplot3, algoplot4, algoplot5, algoplot6, algoplot7, algoplot8,
          nrow = 8, ncol = 1, align = "v")
ggsave("algo_1col.png", width = 24.5, height = 93.4, units = "cm", dpi = 1000)

ggarrange(algoplot1, algoplot2, algoplot3, algoplot4, algoplot5, algoplot6, algoplot7, algoplot8,
          nrow = 4, ncol = 2, align = "v")
ggsave("algo_2col.png", width = 49, height = 46.7, units = "cm", dpi = 1000)



ggarrange(algoplot4, algoplot5, algoplot2,
          nrow = 3, ncol = 1, align = "v")
ggsave("algo_sorted1.png", width = 24.5, height = 35, units = "cm", dpi = 1000)

ggarrange(algoplot3, algoplot7, algoplot1,
          nrow = 3, ncol = 1, align = "v")
ggsave("algo_sorted2.png", width = 24.5, height = 35, units = "cm", dpi = 1000)



ggarrange(algoplot2, algoplot4, algoplot5,
          nrow = 2, ncol = 2, align = "v")
ggsave("algo_sorted_ppt1.png", width = 49, height = 23.35, units = "cm", dpi = 1000)

ggarrange(algoplot7, algoplot3, algoplot1,
          nrow = 2, ncol = 2, align = "v")
ggsave("algo_sorted_ppt2.png", width = 49, height = 23.35, units = "cm", dpi = 1000)




# Legend 

algo <- "ANN"
ggplot.algo.df <- subset(ggplot.df, setup %in% c(algo, paste0("tuned_", algo))) #Include both tuned and untuned
ggplot.algo.df <- ggplot.algo.df[1:100,]

ggplot.algo.df$group <- ifelse(grepl("tuned", ggplot.algo.df$setup), "Tuned ", "Untuned ") #Note the space after the words
ggplot.algo.df$linetype <- ifelse(1:100 <= 50, "Full", "Truncated") #Create a linetype column
ggplot.algo.df$combined_group <- paste0(ggplot.algo.df$group, ggplot.algo.df$linetype)

ggplot(ggplot.algo.df, aes(x = f.F, colour = combined_group, linetype = combined_group)) +  # Corrected aes mapping
  stat_density(geom = "line", position = "identity", size=0.9) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        ###
        plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.key = element_blank(),
        legend.direction = "horizontal",
        legend.position = "bottom",
        legend.text = element_text(size = 14, family = "Calibri"),
        #legend.title = element_text(size = 14, family = "Calibri"),
        legend.title = element_blank(),
        legend.key.width = unit(1, "cm"),
        legend.key.spacing.x = unit(0.5, 'cm')) +
  labs(y = "Density", x = "False predictions", colour = "SDM algorithm      ", linetype = "SDM algorithm      ") + 
  scale_color_manual(values = c("Tuned Full" = "#332288", "Untuned Full" = "#332288", "Tuned Truncated" = "#88CCEE", "Untuned Truncated" = "#88CCEE"),
                     breaks = c("Tuned Full", "Tuned Truncated", "Untuned Full", "Untuned Truncated"), 
                     labels = c("Before tuning, full data", "After tuning, full data", "Before tuning, truncated data",  "After tuning, truncated data")) + 
  scale_linetype_manual(values = c("Tuned Full" = "solid", "Untuned Full" = "dashed", "Tuned Truncated" = "solid", "Untuned Truncated" = "dashed"),
                        breaks = c("Tuned Full", "Tuned Truncated", "Untuned Full", "Untuned Truncated"), 
                        labels = c("Before tuning, full data", "After tuning, full data", "Before tuning, truncated data",  "After tuning, truncated data")) + 
  guides(colour = guide_legend(nrow = 2, override.aes = list(linetype = c("solid", "solid", "dashed", "dashed")))) # Added nrow = 2

ggsave("Algo_tuned_legend.png", width = 24.5, height = 12, units = "cm", dpi = 1200)





